import {useEffect,useRef,useState} from 'react';
import {useImportTeamRecord} from '../../lib/importTeamClient';
import {HANDOFF_KEY,HANDOFF_STATUSES,emptyHandoff,validateImportHandoffs,handoffActor} from '../../lib/importTeamHandoffs';
const EMPTY=[];
const fields=[['issue','이슈·특이사항'],['action','처리 방법·대응 결과'],['caution','주의사항'],['checks','체크사항']];
const stamp=event=>event?`${event.userName} (${event.userId}) · ${new Date(event.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}`:'최근 50회 이력 내 변경 없음';
export default function HandoffTool(){
 const record=useImportTeamRecord(HANDOFF_KEY,EMPTY);
 const [draft,setDraft]=useState(null),[editId,setEditId]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('ALL'),[search,setSearch]=useState('');
 const lock=useRef(false),busy=record.loading||record.saving,stale=draft&&draft.revision!==record.revision;
 useEffect(()=>{const warn=e=>{if(draft){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft]);
 function start(row){if(draft&&!confirm('작성 중인 초안을 비우고 다른 항목을 열까요?'))return;setEditId(row?.id||null);setDraft({... (row||emptyHandoff()),revision:record.revision});setError('');}
 async function saveValue(value){if(lock.current||busy)return false;lock.current=true;setError('');setNotice('');try{validateImportHandoffs(value);await record.save(value);setNotice('공동 저장 완료 · 계정 이력 기록됨');return true;}catch(e){setError(e.message);return false;}finally{lock.current=false;}}
 async function submit(e){e.preventDefault();if(stale||!draft)return;const {revision,...row}=draft;if(editId&&!record.value.some(item=>item.id===editId)){setError('다른 직원이 삭제한 항목입니다. 초안은 유지됩니다.');return;}const value={...row,id:editId||crypto.randomUUID()};if(await saveValue(editId?record.value.map(item=>item.id===editId?value:item):[...record.value,value])){setDraft(null);setEditId(null);}}
 const rows=record.value.filter(row=>(filter==='ALL'||row.status===filter)&&[row.title,row.issue,row.action,row.caution,row.checks].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(b.priority==='IMPORTANT')-(a.priority==='IMPORTANT'));
 return <section className="handoff-tool">
  <header><div><h2>수입부 인수인계·특이사항</h2><p>이슈별 처리 방법, 주의사항과 확인할 내용을 팀과 공유합니다. 저장 시 로그인 계정과 변경 전후 내용이 기록됩니다.</p></div><button disabled={busy||!!draft} onClick={()=>start(null)}>+ 인수인계 추가</button></header>
  <div className="toolbar"><input aria-label="인수인계 검색" placeholder="이슈·처리 방법·주의사항 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="인수인계 상태" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">전체 상태</option>{Object.entries(HANDOFF_STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button disabled={busy} onClick={()=>record.reload().catch(e=>setError(e.message))}>최신 자료 조회 · 초안 유지</button><span>저장 버전 {record.revision}</span></div>
  {(error||record.error)&&<p role="alert" className="error">{error||record.error}</p>}{notice&&<p role="status">{notice}</p>}
  {draft&&<form onSubmit={submit}><h3>{editId?'인수인계 수정':'새 인수인계'}</h3>{stale&&<p className="error">다른 직원의 변경이 있습니다. 최신 목록과 초안을 비교하세요. <button type="button" onClick={()=>setDraft({...draft,revision:record.revision})}>비교 완료 · 초안 재확인</button></p>}<fieldset disabled={busy}><label>제목<input required maxLength={160} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="toolbar"><label>상태<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(HANDOFF_STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>중요도<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}><option value="NORMAL">일반</option><option value="IMPORTANT">중요</option></select></label></div><div className="field-grid">{fields.map(([key,label])=><label key={key}>{label}<textarea required={key==='issue'} rows={4} maxLength={2000} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}</div><div className="toolbar"><button type="submit" disabled={!!stale}>공동 저장 · 계정 이력 남기기</button><button type="button" onClick={()=>{setDraft(null);setEditId(null);}}>초안 취소</button></div></fieldset></form>}
  {record.loading?<p>공동 자료 불러오는 중…</p>:!rows.length?<p>표시할 인수인계가 없습니다.</p>:<div className="handoff-grid">{rows.map(row=><article className={row.priority==='IMPORTANT'?'important':''} key={row.id}><h3>{row.priority==='IMPORTANT'?'중요 · ':''}{row.title}</h3><strong>{HANDOFF_STATUSES[row.status]}</strong>{fields.map(([key,label])=><div key={key}><h4>{label}</h4><p>{row[key]||'—'}</p></div>)}<small>{stamp(handoffActor(record.history,row.id))}</small><div className="toolbar"><button disabled={busy||!!draft} onClick={()=>start(row)}>수정·완료 처리</button><button disabled={busy||!!draft} onClick={()=>{if(confirm('이 인수인계를 삭제할까요? 변경 이력에는 삭제 전 내용과 계정이 남습니다.'))saveValue(record.value.filter(item=>item.id!==row.id));}}>삭제</button></div></article>)}</div>}
  <details><summary>변경 전후 · 계정 로그 (최근 50회)</summary>{[...record.history].reverse().map(event=><article key={event.revision}><strong>버전 {event.revision} · {stamp(event)}</strong>{event.changes?.map(change=><div className="field-grid" key={change.id}>{[['변경 전',change.before],['변경 후',change.after]].map(([label,row])=><div key={label}><h4>{label}</h4>{row?<><b>{row.title} · {HANDOFF_STATUSES[row.status]} · {row.priority==='IMPORTANT'?'중요':'일반'}</b>{fields.map(([key,name])=><p key={key}>{name}: {row[key]||'—'}</p>)}</>:<p>항목 없음</p>}</div>)}</div>)}</article>)}{!record.history.length&&<p>아직 변경 이력이 없습니다.</p>}</details>
  <style jsx>{`
   .handoff-tool{color:#172b4d;font-size:14px;min-width:0}header,.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:12px}header>div{flex:1 1 360px}h2{font-size:19px;margin:0 0 6px}h3{font-size:16px;margin:0 0 8px}h4{font-size:13px;margin:10px 0 3px}p{white-space:pre-wrap;overflow-wrap:anywhere;margin:5px 0 10px}button,input,select,textarea{font:inherit;padding:8px;border:1px solid #a5b8d1;border-radius:5px;max-width:100%;min-height:36px}button{background:#eef4ff;color:#194caa;cursor:pointer}button:disabled{opacity:.5;cursor:default}input,textarea{width:100%;min-width:0}.toolbar>input{flex:1 1 260px}.field-grid,.handoff-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{display:flex;flex-direction:column;gap:5px;margin-bottom:10px}form,article,details{border:1px solid #d5deeb;border-radius:8px;padding:14px;margin:12px 0;background:#f8fafc;min-width:0}article.important{border-left:4px solid #df930c}fieldset{border:0;margin:0;padding:0;min-width:0}.error{background:#fff0ee;color:#a22;padding:10px}small{color:#52647c}summary{cursor:pointer;font-weight:600}@media(max-width:900px){.field-grid,.handoff-grid{grid-template-columns:1fr}}
  `}</style>
 </section>;
}
