SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF OBJECT_ID(N'dbo.WebFarmQualityCase',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.WebFarmQualityCase (
 CaseKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 OrderYear INT NOT NULL, SourceKey INT NOT NULL, ProdKey INT NOT NULL,
 FarmName NVARCHAR(200) NOT NULL, FarmKey INT NULL, ProductName NVARCHAR(300) NOT NULL,
 Title NVARCHAR(200) NOT NULL, Status NVARCHAR(20) NOT NULL,
 DueDate DATE NULL, AppliedWeek INT NULL, Version INT NOT NULL DEFAULT 1,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CreatedBy NVARCHAR(100) NOT NULL, CreatedByName NVARCHAR(100) NOT NULL,
 CreateRequest UNIQUEIDENTIFIER NOT NULL UNIQUE
 );
 CREATE INDEX IX_WebFarmQualityCase_Year ON dbo.WebFarmQualityCase(OrderYear,UpdatedAt);
END;
IF OBJECT_ID(N'dbo.WebFarmQualityEvent',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.WebFarmQualityEvent (
 EventKey BIGINT IDENTITY PRIMARY KEY, CaseKey UNIQUEIDENTIFIER NOT NULL,
 RequestKey UNIQUEIDENTIFIER NOT NULL UNIQUE, PayloadHash CHAR(64) NOT NULL,
 Kind NVARCHAR(20) NOT NULL, Body NVARCHAR(4000) NOT NULL,
 AuthorId NVARCHAR(100) NOT NULL, AuthorName NVARCHAR(100) NOT NULL, Department NVARCHAR(100) NOT NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 BeforeStatus NVARCHAR(20) NULL, AfterStatus NVARCHAR(20) NOT NULL,
 EventDate DATE NULL, DueDate DATE NULL, AppliedWeek INT NULL,
 CONSTRAINT FK_WebFarmQualityEvent_Case FOREIGN KEY(CaseKey) REFERENCES dbo.WebFarmQualityCase(CaseKey)
 );
 CREATE INDEX IX_WebFarmQualityEvent_Case ON dbo.WebFarmQualityEvent(CaseKey,EventKey);
END;
IF OBJECT_ID(N'dbo.WebFarmQualityEvidence',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.WebFarmQualityEvidence (
 EvidenceKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 OrderYear INT NOT NULL,
 EventKey BIGINT NULL,
 FileName NVARCHAR(200) NOT NULL,
 MimeType NVARCHAR(40) NOT NULL,
 ByteSize INT NOT NULL,
 Content VARBINARY(MAX) NOT NULL,
 CreatedBy NVARCHAR(100) NOT NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 ExpiresAt DATETIME2 NOT NULL,
 CONSTRAINT FK_WebFarmQualityEvidence_Event FOREIGN KEY(EventKey) REFERENCES dbo.WebFarmQualityEvent(EventKey)
 );
 CREATE INDEX IX_WebFarmQualityEvidence_Event ON dbo.WebFarmQualityEvidence(EventKey,EvidenceKey);
 CREATE INDEX IX_WebFarmQualityEvidence_Draft ON dbo.WebFarmQualityEvidence(OrderYear,CreatedBy,ExpiresAt) WHERE EventKey IS NULL;
END;
COMMIT;
