import {useMemo,useState} from 'react';

const fmt=value=>value==null||value===''||!Number.isFinite(Number(value))?'확인 필요':Number(value).toLocaleString('ko-KR',{maximumFractionDigits:1});
const count=value=>Number(value||0).toLocaleString('ko-KR');
const parentWeek=value=>Number(String(value||'').match(/\d+/)?.[0]||0);
const text=value=>String(value??'').trim();

/** Full active-source audit list. It deliberately does not inherit graph unit filters. */
export default function FarmQualityCoverage({coverage}){
 const [open,setOpen]=useState(false),[scope,setScope]=useState('DEFAULT'),[status,setStatus]=useState('ALL'),[search,setSearch]=useState('');
 const available=Boolean(coverage),safe=coverage||{};
 const query=search.trim().toLowerCase();
 const rows=useMemo(()=>[...(safe.rows||[])].filter(row=>{
  const inDefaultRange=row.rangeStatus==='IN_RANGE'||row.rangeStatus==='UNKNOWN_WEEK';
  if(scope==='DEFAULT'&&!inDefaultRange)return false;
  if(scope==='OUT_OF_RANGE'&&row.rangeStatus!=='OUT_OF_RANGE')return false;
  if(status==='INCOMPLETE'&&(!inDefaultRange||row.eligible!==false))return false;
  if(!query)return true;
  return [row.customerName,row.farmName,row.productName,row.orderWeek,row.unit,...(row.reasons||[])].join(' ').toLowerCase().includes(query);
 }).sort((left,right)=>Number(right.orderYear||0)-Number(left.orderYear||0)||parentWeek(right.orderWeek)-parentWeek(left.orderWeek)||Number(right.sourceKey||0)-Number(left.sourceKey||0)),[safe.rows,scope,status,query]);
 const activeTotal=Number(safe.activeTotal??safe.rows?.length??0),deletedCount=Number(safe.deletedCount??0),sourceTotal=Number(safe.sourceTotal??activeTotal+deletedCount),inRangeCount=Number(safe.inRangeCount??0),outOfRangeCount=Number(safe.outOfRangeCount??0),invalidWeekCount=Number(safe.invalidWeekCount??0),eligible=Number(safe.eligibleCount??0),incomplete=Number(safe.incompleteCount??0);
 const reason=row=>Array.isArray(row.reasons)&&row.reasons.length?row.reasons.join(' · '):row.rangeStatus==='OUT_OF_RANGE'?'선택 기간 밖':row.eligible===false?'검토 필요':'분석 포함';
 const state=row=>row.rangeStatus==='OUT_OF_RANGE'?'기간 밖':row.eligible===false?'보완 필요':'분석 포함';
 const showOutside=()=>{setScope('OUT_OF_RANGE');setStatus('ALL');setOpen(true)};
 if(!available)return <section className="coverage coverage-unavailable" aria-label="불량 원본 범위"><h2>불량 원본 범위</h2><p role="status">원본 범위를 불러오지 못했습니다. 새로고침 후 다시 확인하세요.</p><style jsx>{`.coverage{border:1px solid #cddbea;background:#fff;border-radius:7px;padding:10px;margin-bottom:12px}.coverage h2{margin:0 0 4px}.coverage p{margin:0;color:#9a5b04}`}</style></section>;
 return <section className="coverage" aria-label="불량 원본 범위">
  <div className="coverage-head"><div><h2>불량 원본 범위</h2><small>그래프 단위 필터와 무관하게 선택 연도의 활성 원본을 보존합니다. 기본 목록은 기간 내·차수 미상이며, 자동 감지 이슈는 반복 패턴 후보일 뿐 전체 불량을 뜻하지 않습니다.</small></div><strong>활성 {count(activeTotal)}건</strong></div>
  <div className="coverage-summary"><span>원본 합계 <b>{count(sourceTotal)}</b></span><span>활성 원본 <b>{count(activeTotal)}</b></span><span>기간 내 <b>{count(inRangeCount)}</b></span><button className="coverage-count" aria-pressed={scope==='OUT_OF_RANGE'} onClick={showOutside}>기간 밖 <b>{count(outOfRangeCount)}</b></button><span>차수 미상 <b>{count(invalidWeekCount)}</b></span><span>분석 포함 <b>{count(eligible)}</b></span><span>보완 필요 <b>{count(incomplete)}</b></span><span>삭제 <b>{count(deletedCount)}</b></span></div>
  <div className="coverage-controls"><label>원본 검색 <input aria-label="불량 원본 검색" value={search} onChange={event=>setSearch(event.target.value)} placeholder="거래처 · 농장 · 품목 검색"/></label><div role="group" aria-label="원본 범위 필터"><button aria-pressed={scope==='DEFAULT'} onClick={()=>{setScope('DEFAULT');setStatus('ALL')}}>기본 범위</button><button aria-pressed={scope==='ALL_ACTIVE'} onClick={()=>{setScope('ALL_ACTIVE');setStatus('ALL')}}>전체 활성</button><button aria-pressed={scope==='OUT_OF_RANGE'} onClick={showOutside}>기간 밖</button></div><div role="group" aria-label="원본 상태 필터"><button aria-pressed={status==='ALL'} onClick={()=>setStatus('ALL')}>전체</button><button aria-pressed={status==='INCOMPLETE'} onClick={()=>{setScope('DEFAULT');setStatus('INCOMPLETE')}}>보완 필요</button></div><button className="coverage-toggle" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?'원본 목록 접기':'원본 목록 펼치기'} · {count(rows.length)}건</button></div>
  {open&&<div className="coverage-table-wrap"><table><thead><tr><th>원발생</th><th>거래처</th><th>농장</th><th>품목</th><th>수량</th><th>상태 / 사유</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.sourceKey||'source'}-${index}`} className={row.eligible===false?'incomplete':''}><td>{text(row.orderYear)} · {text(row.orderWeek)}</td><td>{text(row.customerName)||'거래처 미상'}</td><td>{text(row.farmName)||'농장 미상'}</td><td>{text(row.productName)||'품목 미상'}</td><td>{fmt(row.quantity)} {text(row.unit)}</td><td><b>{state(row)}</b><small>{reason(row)}</small></td></tr>)}{!rows.length&&<tr><td colSpan="6">조건에 맞는 활성 원본이 없습니다.</td></tr>}</tbody></table></div>}
  <style jsx>{`
   .coverage{border:1px solid #cddbea;background:#fff;border-radius:7px;padding:10px;margin-bottom:12px;color:#19304f}.coverage button,.coverage input{font:inherit;border:1px solid #c4d2e5;border-radius:5px;padding:6px 9px;color:#19304f;background:white}.coverage button{cursor:pointer}.coverage button:hover{background:#edf5ff;border-color:#76a5de}.coverage button[aria-pressed=true]{background:#205db5;color:white;border-color:#205db5}.coverage-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.coverage-head h2{margin:0 0 3px}.coverage-head small{display:block;color:#586b84;line-height:1.4}.coverage-head>strong{white-space:nowrap;color:#174e99;font-size:16px}.coverage-summary,.coverage-controls{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:8px}.coverage-summary span,.coverage-count{border:1px solid #d9e4f1;background:#f7faff;border-radius:4px;padding:3px 6px;font-size:12px}.coverage-count{color:#19304f}.coverage-count[aria-pressed=true]{background:#205db5;color:white}.coverage-controls label{display:flex;align-items:center;gap:5px;font-size:12px}.coverage-controls input{min-width:230px}.coverage-controls button{font-size:12px}.coverage-toggle{margin-left:auto}.coverage-table-wrap{max-height:380px;overflow:auto;border:1px solid #dbe4ef;margin-top:8px}.coverage table{width:100%;border-collapse:collapse;min-width:860px;font-size:12px}.coverage th{position:sticky;top:0;z-index:1;background:#eaf2fc;color:#193f78;text-align:left}.coverage th,.coverage td{padding:6px 8px;border-bottom:1px solid #e2e8f0;vertical-align:top;white-space:nowrap}.coverage td:nth-child(3),.coverage td:nth-child(4){max-width:220px;overflow:hidden;text-overflow:ellipsis}.coverage td:last-child{white-space:normal;min-width:220px}.coverage td:last-child b{display:block;font-size:11px}.coverage td:last-child small{display:block;color:#66788e;margin-top:2px}.coverage tr.incomplete{background:#fff7e8}.coverage tr.incomplete td:last-child b{color:#9a5b04}@media(max-width:900px){.coverage-controls input{min-width:170px}.coverage-toggle{margin-left:0}.coverage-table-wrap{max-height:340px}}@media(max-width:760px){.coverage{padding:8px}.coverage-head{display:block}.coverage-head>strong{display:block;margin-top:5px}.coverage-controls label{width:100%}.coverage-controls input{flex:1;min-width:0}.coverage-table-wrap{max-height:320px}.coverage table{min-width:760px}}
  `}</style>
 </section>;
}
