// Display-only labels. Never use these values as storage keys, employee names,
// farm names, varieties, export fields, or replacements for user-authored text.
export const CHECKLIST_COUNTRY_KO = Object.freeze({
  Netherlands: '네덜란드', Tailandia: '태국', Australia: '호주',
  Colombia: '콜롬비아', China: '중국', Vietnam: '베트남', Ecuador: '에콰도르',
  General: '공통 업무', 'Holex / EZ': 'Holex / EZ',
  'China / Ecuador': '중국 / 에콰도르', Pagos: '월별 결제',
});

export const CHECKLIST_WEEKDAY_KO = Object.freeze({
  lunes: '월', martes: '화', miercoles: '수', jueves: '목',
  viernes: '금', sabado: '토', domingo: '일',
});

export const CHECKLIST_MONTHLY_KO = Object.freeze({
  '포딩비 결제 정리하기': '포워딩비 결제 내역 정리',
  'Tiba · 수입 수량 네노바/한국': 'Tiba · 네노바/한국 수입 수량 확인',
  'Resto de fincas · rosas & claveles': '기타 농장 · 장미·카네이션 결제',
  Hortensias: '수국 결제',
  'Empleados Colombia + 보딩업체': '콜롬비아 직원 및 포워딩업체 결제',
  'Justificar gastos tarjeta del departamento de importación': '수입부 법인카드 지출 증빙 정리',
});

export const CHECKLIST_TASK_KO = Object.freeze({
  'Comprobar Lista de Empaquetado de Netherlands y que esté en el Drive': '네덜란드 패킹리스트 확인 및 드라이브 업로드 여부 확인',
  'Comprobar precios de todas las variedades de EZ y Holex que estemos pidiendo': '발주 중인 EZ·Holex 전체 품종의 가격 확인',
  'Comprobar orden del Miércoles en la página web de Holex/EZ si tienen ETA Miércoles': '수요일 도착 주문이 있으면 Holex/EZ 웹사이트에서 주문 확인',
  'Preguntar si tienen pedido de Netherlands para el Miércoles si no lo han hecho': '수요일 네덜란드 주문이 아직 없으면 발주 여부 문의',
  'Comprobar Lista de Empaquetado de Tailandia y que esté en el Drive': '태국 패킹리스트 확인 및 드라이브 업로드 여부 확인',
  'Preguntar disponibilidad de variedades de Tailandia': '태국 품종별 공급 가능 여부 문의',
  'Hacer 원가자료 de Tailandia': '태국 원가자료 작성',
  'Hacer 원가자료 de Australia': '호주 원가자료 작성',
  'Si hay pedido de Australia: pedir documentos, subirlos al Drive, mandarlos por email, subir horarios en Kakao': '호주 주문이 있으면 서류 요청·드라이브 업로드·이메일 발송 후 카카오톡에 일정 공유',
  'Packing List (1차) — comprobar invoices con packing (cantidad y precios)': '1차 패킹리스트와 인보이스의 수량·가격 대조',
  'Subir packings también de los AWB': 'AWB별 패킹리스트도 업로드',
  'Fitos — en los claveles siempre debe figurar NON LMO': '식물검역증명서 확인 · 카네이션은 NON LMO 표기 필수',
  'Mandar correos (백상 y 선율)': '백상·선율에 이메일 발송',
  'Subir documentos al Drive': '서류 드라이브 업로드',
  'Revisar aviones del fin de semana': '주말 항공편 확인',
  'Excel de % confirmados del 차주 pasado': '지난 차주 확정 비율 엑셀 정리',
  '원가자료': '원가자료 작성',
  '발주 1차 + 2차 (수국 no)': '1차·2차 발주 · 수국 제외',
  '9:00 — Comprobar estado de vuelo del pedido con llegada Domingo': '09:00 · 일요일 도착 주문의 항공편 상태 확인',
  '9:00 — Comprobar documentos: AWB, Phyto, CO, CI (cantidades, nº invoice, fecha, items)': '09:00 · AWB·식물검역증명서·원산지증명서·인보이스 확인 (수량·인보이스 번호·날짜·품목)',
  '9:30 — Crear packing list y subir al ERP (revisar total)': '09:30 · 패킹리스트 작성 및 ERP 업로드 · 합계 확인',
  '9:30 — Enviar PL del proveedor a nenova e Import cost': '09:30 · 공급업체 패킹리스트를 네노바·Import cost에 전달',
  '10:30 — Mandar documentos revisados (AWB, CI, Phyto, CO, PL CL) y subir al Drive': '10:30 · 검토한 서류 (AWB·CI·식물검역증명서·CO·PL CL) 전달 및 드라이브 업로드',
  'Enviar claims': '클레임 전달',
  'Revisar incrementos de precios, claims y tarifas de vuelo': '가격 인상·클레임·항공 운임 확인',
  'Comprobar Unipass para que todo esté en 반입 완료': '유니패스에서 전체 화물의 반입 완료 여부 확인',
  'Comprobar si hay quejas que hayan mandado en el fin de semana': '주말 접수된 불만·클레임 확인',
  '불량차감 확인하고 차장님에게 드리기': '불량 차감 내역 확인 후 차장님께 전달',
  'Comprobar pedido de Netherlands si hay para ETA Miércoles': '수요일 도착 예정 네덜란드 주문 확인',
  'Comprobar que no haya problemas con el pedido del Miércoles': '수요일 주문의 문제 여부 확인',
  'Comprobar Proforma si hay pedido del Miércoles y hacer 원가자료': '수요일 주문이 있으면 견적송장 확인 및 원가자료 작성',
  'Hacer pedido de Tailandia y mandar orden al grupo de Importación': '태국 발주 후 수입부 단체방에 주문 공유',
  'Hacer pedido de Vietnam si lo hay': '베트남 주문이 있으면 발주',
  'Si hay pedido hecho: mandar papeles, subir al Drive y mandar horarios': '발주한 주문의 서류 전달·드라이브 업로드 및 일정 공유',
  'Hacer pedido de Australia si lo hay': '호주 주문이 있으면 발주',
  'Preguntar si tienen pedido de Australia y mandar orden al grupo de Importación': '호주 주문 여부 문의 후 수입부 단체방에 주문 공유',
  'Si hay pedido de Australia para el Martes: comprobar 반입 완료': '화요일 도착 호주 주문이 있으면 반입 완료 여부 확인',
  'Comprobar aviones si hay': '항공편이 있으면 운항 상태 확인',
  '원가자료 — rellenarlo con el packing list y subirlo a 수입방': '패킹리스트 기준 원가자료 작성 후 수입방에 공유',
  'Revisar excel de Karen': 'Karen 엑셀 확인',
  'Hacer el 지출결의서 que manda 선율': '선율에서 전달한 내역으로 지출결의서 작성',
  'Revisar informes de calidad': '품질 보고서 확인',
  'Meeting Importación — 수입부 회의': '수입부 회의',
  'Estar atento a additions y cancelaciones': '추가·취소 주문 수시 확인',
  'Mandar documentos de Netherlands y subir lista de empaquetado si hay pedido del Miércoles': '수요일 네덜란드 주문이 있으면 서류 전달 및 패킹리스트 업로드',
  'Mandar horario del vuelo en los tres grupos': '항공 일정을 3개 단체방에 공유',
  'Hacer pedido de Netherlands, dividiendo por EZ y Holex': 'EZ·Holex로 구분하여 네덜란드 발주',
  'Pedir factura de Vietnam y preparar el pago': '베트남 인보이스 요청 및 결제 준비',
  'Si hay pedido de Australia y ha llegado el día anterior: comprobar 반입 완료': '전날 도착한 호주 주문이 있으면 반입 완료 여부 확인',
  'Comprobar aviones': '항공편 운항 상태 확인',
  'Organizar defectuosos': '불량 내역 정리',
  'Subir 2차 수국': '2차 수국 자료 업로드',
  '9:00 — Comprobar estado de vuelo del pedido con llegada hoy': '09:00 · 오늘 도착 주문의 항공편 상태 확인',
  '9:30 — Crear packing list y subir al ERP': '09:30 · 패킹리스트 작성 및 ERP 업로드',
  '10:30 — Mandar documentos revisados y subir al Drive': '10:30 · 검토한 서류 전달 및 드라이브 업로드',
  'Enviar pedido a Melody 00-2 (Arrival Domingo)': 'Melody에 00-2 주문 전달 · 일요일 도착',
  '9:00 — Revisar y enviar a Seonyul documentos de Ecuador (AWB, Customs Invoice, Phyto) y subir al Drive': '09:00 · 에콰도르 서류 (AWB·통관 인보이스·식물검역증명서) 검토 후 선율에 전달 및 드라이브 업로드',
  '10:30 — Revisar total del pedido': '10:30 · 주문 합계 확인',
  'Enviar pedido Ecuador (Arrival próximo Viernes)': '에콰도르 주문 전달 · 다음 금요일 도착',
  'Reunión particular por empleado — 직원별 개별 면담': '직원별 개별 면담',
  'Comprobar que toda la orden de Netherlands esté correcta, ver si hay agregados': '네덜란드 전체 주문 및 추가 주문 여부 확인',
  'Comprobar que toda la orden de Tailandia esté correcta, ver si hay agregados': '태국 전체 주문 및 추가 주문 여부 확인',
  'Packing List (2차) — subir packing list 2차 콜카장': '2차 콜카장 패킹리스트 업로드',
  'Subir packing list aviones 코카장 콜수국 2차': '코카장·콜수국 2차 항공편 패킹리스트 업로드',
  '지출결의서 que manda 선율': '선율에서 전달한 지출결의서 확인',
  'Meeting Ventas — reunión con el equipo de ventas': '영업팀 회의',
  'Informar issues 2차 — Rosas': '2차 장미 이슈 공유',
  'Informar issues 2차 — Carnation': '2차 카네이션 이슈 공유',
  'Informar issues 2차 — Alstromeria': '2차 알스트로메리아 이슈 공유',
  'Informar issues 2차 — Ruscus': '2차 루스커스 이슈 공유',
  'Informar issues 2차 — Hortensias': '2차 수국 이슈 공유',
  'Crear pedido China 00-1 (Arrival próximo Miércoles)': '중국 00-1 발주 · 다음 수요일 도착',
  'Cloud compare precios y ordenar mejor deal de las farms': '클라우드에서 농장별 가격 비교 후 최적 조건으로 발주',
  'Actualizar excel de quejas y comprobar que las hayan mandado todas': '클레임 엑셀 갱신 및 전체 전달 여부 확인',
  'Comprobar Proforma Netherlands, hacer 원가자료': '네덜란드 견적송장 확인 및 원가자료 작성',
  'Preparar email fin de semana': '주말 안내 이메일 준비',
  'Confirmación de Tailandia y fotos de las variedades': '태국 주문 확정 및 품종 사진 확인',
  'Comprobar orden del Domingo en la página web de Holex/EZ': 'Holex/EZ 웹사이트에서 일요일 주문 확인',
  '운임비 y mandarlo a 명훈님': '운임비 정리 후 명훈님께 전달',
  '발주 2차 de 수국': '수국 2차 발주',
  'Correos 2차': '2차 이메일 발송',
  'Excel de 입고량 → mandar a 이사님': '입고량 엑셀 정리 후 이사님께 전달',
  'Subir al Drive 2차': '2차 자료 드라이브 업로드',
  '⭐ 신라 확인하기 — 수국 2차 발주': '⭐ 신라 주문 확인 · 수국 2차 발주',
  'Informar issues — Rosas': '장미 이슈 공유',
  'Informar issues — Carnation': '카네이션 이슈 공유',
  'Informar issues — Alstromeria': '알스트로메리아 이슈 공유',
  'Informar issues — Ruscus': '루스커스 이슈 공유',
  'Informar issues — Hortensias': '수국 이슈 공유',
  '9:00 — Comprobar estado de vuelo del pedido con llegada Viernes (Ecuador)': '09:00 · 금요일 도착 에콰도르 주문의 항공편 상태 확인',
  'Cloud compare prices, ordenar mejor deal de farms, confirmar cantidades y reorder': '클라우드에서 농장별 가격 비교 후 최적 조건으로 발주 · 수량 확정 및 재발주',
  'Añadir items a Melody si no encuentras las flores ordenadas': '발주한 꽃을 구하지 못하면 Melody 주문에 품목 추가',
  'Hacer lista de Problemas y preparar excel de porcentaje de confirmaciones': '문제 목록 정리 및 주문 확정 비율 엑셀 준비',
  '주말 스케쥴 공유': '주말 일정 공유',
  'Comprobar papeles de Tailandia y Netherlands': '태국·네덜란드 서류 확인',
  'Revisar total del pedido': '주문 합계 확인',
});

export const CHECKLIST_ERROR_KO = Object.freeze({
  'Introduce al menos la fecha de inicio.': '휴가 시작일을 입력하세요.',
  'Introduce el número de días (mayor que 0).': '휴가 일수를 0보다 크게 입력하세요.',
  'Escribe el nombre de la finca.': '농장명을 입력하세요.',
  'Introduce el número de cajas (mayor que 0).': '박스 수를 0보다 크게 입력하세요.',
  'Introduce un precio válido en USD.': '유효한 USD 단가를 입력하세요. 0 이상이어야 합니다.',
});

const label = (mapping, original) => Object.hasOwn(mapping, original) ? mapping[original] : original;
export const checklistTaskLabel = original => label(CHECKLIST_TASK_KO, original);
export const checklistCountryLabel = original => label(CHECKLIST_COUNTRY_KO, original);
export const checklistMonthlyLabel = task => `${task.day}일 · ${label(CHECKLIST_MONTHLY_KO, task.desc)}`;
export function checklistWeekdayLabel(day, full = false) {
  const korean = label(CHECKLIST_WEEKDAY_KO, day.id);
  return Object.hasOwn(CHECKLIST_WEEKDAY_KO, day.id) ? `${korean}${full ? '요일' : ''}` : (full ? day.full : day.label);
}
export const checklistErrorLabel = message => label(CHECKLIST_ERROR_KO, message);
