const assert = require('assert');
const fs = require('fs');
const path = require('path');

const pagePath = path.join(__dirname, '..', 'pages', 'stats', 'china-order-download.js');
const page = fs.readFileSync(pagePath, 'utf8');

assert.match(page, /import \{ apiGet \} from '\.\.\/\.\.\/lib\/useApi'/, '조회는 공통 인증 API 클라이언트를 사용한다');
assert.match(page, /apiGet\('\/api\/stats\/china-order-download', params\)/, '중국 주문 조회 API를 호출한다');
assert.match(page, /selected \? \{ year: selected\.year, majorWeek: selected\.majorWeek \} : \{\}/, '기본 달력 조회는 파라미터를 생략하고 이동 조회는 연도와 대차수를 함께 보낸다');
assert.match(page, /if \(selected && \(Number\(result\.scope\.year\)[\s\S]*요청한 중심 차수와 조회 결과가 다릅니다/, '성공 응답도 요청한 중심 연도·차수와 불일치하면 거부한다');
assert.match(page, /result\.readOnly !== true/, '응답의 읽기 전용 계약을 확인한다');
assert.match(page, /Array\.isArray\(result\.availableCycles\)/, '화면 차수 선택은 서버가 반환한 실제 달력에 한정한다');
assert.match(page, /import \{ buildChinaOrderReport, selectChinaOrderSubweek \}/, '선택한 세부차수는 공유 모델 선택 helper로 구성한다');
assert.match(page, /const \[selectedColumnKey, setSelectedColumnKey\] = useState\(''\)/, '선택된 세부차수를 독립 상태로 보관한다');
assert.match(page, /find\(column => !column\.empty && column\.offset === 0\)[\s\S]*Math\.abs\(a\.offset\) - Math\.abs\(b\.offset\)/, '중심 메인차수의 첫 실제 세부차수를 우선하고 없으면 가장 가까운 실제 세부차수를 선택한다');
assert.match(page, /aria-label="세부차수"[\s\S]*actualColumns\.map\(column => <option[\s\S]*column\.year\}년 \{column\.orderWeek/, '실제 세부차수만 연도와 전체 주차 라벨로 선택할 수 있다');
assert.match(page, /actualColumns = useMemo\(\(\) => \(report\?\.columns \|\| \[\]\)\.filter\(column => !column\.empty\)/, 'empty placeholder는 선택 가능한 세부차수에서 제외한다');
assert.match(page, /selectChinaOrderSubweek\(report, selectedColumn\.key\)/, '선택 helper에 유효한 단일 세부차수 키를 전달한다');
assert.match(page, /selectedReport\.customerRows\.map/, '화면행은 업체·품목·단위별 주문행에서 만든다');
assert.match(page, /new Set\(annotatedRows\.map\(row => row\.rowKey\)\)/, '검색과 매칭 상태 필터를 helper의 customerRowKeys로 전달한다');
assert.match(page, /selectChinaOrderSubweek\(report, selectedColumn\.key, new Set\(/, 'visibleReport를 단일 세부차수와 필터된 row key로 재선택한다');
assert.match(page, /data-selected-subweek=\{visibleReport\.selectedColumnKey\}/, '표에 현재 단일 세부차수 키를 노출한다');
assert.match(page, /data-column-key=\{visibleReport\.selectedColumnKey\}/, '단일 수량 열에 선택 세부차수 키를 노출한다');
assert.doesNotMatch(page, /visibleReport\.columns\.map|visibleReport\.cycles\.map\(cycle => <(?:col|th|td)/, '화면 수량은 세부차수 열 행렬이 아니라 단일 열이다');
assert.match(page, /<col className="product-col" \/><col className="unit-col" \/><col className="total-col" \/>\{customerMatrix\.customers\.map/, '품목(HF)·단위·합계 고정열 뒤에 업체별 열을 표시한다');
assert.match(page, /buildChinaOrderCustomerMatrix\(visibleReport\)/, '표와 엑셀은 같은 업체행렬 helper를 사용한다');
assert.match(page, /availableCycles\.findIndex[\s\S]*availableCycles\[index \+ delta\]/, '이전/다음은 실제 차수 목록 기준으로 이동한다');
assert.match(page, /matchChinaHfCode\(row, mapping, report\.products \|\| \[\]\)/, '품목별 HF 매칭에 전체 활성 중국 품목을 전달해 고유 fallback을 판별한다');
assert.ok(page.includes("row.custName || ''} ${row.custOrderCode || ''} ${row.prodCode || ''} ${row.prodName || ''}"), '검색은 업체명·CL 코드·품목코드·품목명도 대상으로 한다');
assert.match(page, /customer\.custName \|\| '업체명 미등록'[\s\S]*customer\.custOrderCode \|\| 'CL 미등록'/, '가로 헤더에 업체명(CL)을 함께 표시한다');
assert.match(page, /row\.hf\.hfCode \|\| 'HF 미매칭'/, '사용자 지정 코드번호는 HF 코드이며 미매칭은 명시한다');
assert.match(page, /data-quantity=\{row\.total\}[\s\S]*quantity\(row\.total\)/, '품목별 합계를 별도 고정 셀에 표시한다');
assert.match(page, /data-cust-key=\{customer\.custKey\} data-quantity=\{row\.quantities\[String\(customer\.custKey\)\]\}/, '실제 고객키 기반 업체 셀의 수량을 표시한다');
assert.ok(/localStorage\.getItem[\s\S]*nextMapping = normalizeHfMapping\(saved\.mapping \|\| saved\)[\s\S]*catch \{[\s\S]*nextMapping = normalizeHfMapping\(seedMapping\)/.test(page), '인증된 사용자의 사전이 있을 때만 복원하고 없으면 기본 사전을 사용한다');
assert.ok(page.indexOf("apiGet('/api/auth/me')") < page.indexOf('localStorage.getItem'), '사용자 인증 확인 후에만 사용자별 브라우저 사전을 읽는다');
assert.match(page, /STORAGE_PREFIX.*encodeURIComponent\(userId\)/, '저장 키는 기능과 인증 사용자 ID로 범위를 격리한다');
assert.match(page, /file\.size > MAX_UPLOAD_BYTES/, '5MiB 초과 파일은 사전을 교체하지 않고 거부한다');
assert.match(page, /const id = \+\+uploadId\.current[\s\S]*id !== uploadId\.current/, '업로드 요청 ID로 오래된 업로드 결과가 최신 상태를 덮지 않는다');
assert.match(page, /normalizeHfMapping\(saved\.mapping \|\| saved\)[\s\S]*catch \{[\s\S]*nextMapping = normalizeHfMapping\(seedMapping\)/, '손상되거나 유효하지 않은 사용자 사전은 인증을 실패시키지 않고 기본 사전으로 복구한다');
assert.match(page, /uploadId\.current \+= 1;[\s\S]*downloadId\.current \+= 1;/, '언마운트 때 진행 중인 업로드·다운로드 응답을 무효화한다');
assert.match(page, /if \(id !== downloadId\.current\) return;/, '언마운트된 다운로드는 브라우저 파일 저장을 시작하지 않는다');
assert.match(page, /if \(id === downloadId\.current\) setDownloading\(false\)/, '언마운트 뒤 다운로드 완료가 상태를 갱신하지 않는다');
assert.match(page, /기존 사전은 그대로 유지했습니다/, '잘못된 업로드는 기존 사전을 보존하고 실패를 설명한다');
assert.match(page, /브라우저 저장은 되지 않았습니다/, '저장 공간 부족 때 화면 적용과 영구 저장 실패를 구분한다');
assert.match(page, /accept="\.xlsx"/, '사전 업로드는 XLSX만 허용한다');
assert.match(page, /await workbook\.xlsx\.writeBuffer\(\)/, 'ExcelJS workbook을 브라우저에서 생성한다');
assert.match(page, /disabled=\{busy \|\| !selectedColumn \|\| !visibleReport\?\.rows\.length \|\| !isReportCurrent\}/, '로딩·작업중·빈 결과·미선택 세부차수 또는 오래된 범위에서는 다운로드를 차단한다');
assert.match(page, /anchor\.download = `중국_발주현황_\$\{selectedColumn\.year\}-\$\{selectedColumn\.orderWeek\}\.xlsx`/, '다운로드 파일명은 선택된 연도와 세부차수를 포함한다');
assert.match(page, /업체명, CL 코드, 품목명 또는 HF CODE 검색[\s\S]*disabled=\{!report \|\| busy\}/, '업로드·다운로드 중에는 검색 필터 입력을 잠근다');
assert.match(page, /매칭 상태 필터[\s\S]*disabled=\{!report \|\| busy\}/, '업로드·다운로드 중에는 상태 필터 변경을 잠근다');
assert.match(page, /const reportCenter = report\?\.cycles\?\.\[3\]/, '조회결과 기준 차수는 API scope dates가 아니라 실제 중심 달력 행을 쓴다');
assert.match(page, /report && !isReportCurrent[\s\S]*중심 차수가 변경됐습니다[\s\S]*이전 결과는 다운로드할 수 없습니다/, '차수 선택 변경 시 재조회 안내를 하고 이전 데이터를 새 차수로 오인시키지 않는다');
assert.match(page, /const id = \+\+requestId\.current[\s\S]*id !== requestId\.current/, '경쟁 조회의 오래된 결과는 폐기한다');
assert.match(page, /setReport\(null\)/, '재조회 시작 시 이전 결과를 내보내기 가능한 상태로 남기지 않는다');
assert.match(page, /role="alert"/, '오류를 보조기술에 알린다');
assert.match(page, /role="status"/, '로딩·빈 결과·상태를 보조기술에 알린다');
assert.match(page, /font-size:14px;font-weight:900;line-height:20px/, '선택 수량을 진한 14px 숫자로 표시한다');
assert.match(page, /--product-width:420px;--unit-width:62px;--total-width:98px/, '좌측 고정 정보 폭은 580px로 최소화한다');
assert.match(page, /\.customer-col\{width:146px\}/, '업체별 수량 열을 고정 크기로 만든다');
assert.match(page, /\.fixed-product,.fixed-unit,.fixed-total\{position:sticky/, '품목·단위·총수량을 가로 스크롤에도 고정한다');
assert.match(page, /\.orders-table tbody tr:hover/, '전체 행 hover 상태를 제공한다');
assert.match(page, /overflow:auto;overscroll-behavior:contain/, '업체행렬은 명시 스크롤 영역 안에서 헤더를 고정한다');
assert.match(page, /width:max-content;table-layout:fixed/, '고정 열 기반 내용 폭으로 업체 수량표를 만든다');
assert.match(page, /<tfoot>[\s\S]*customerMatrix\.totals\.map[\s\S]*data-unit-total=\{total\.unit\}/, '단위별 전체/업체별 합계를 표시한다');
assert.match(page, /현재 필터에 포함된 주문의 합계입니다/, '업체 검색시 전체 합계로 오인하지 않도록 안내한다');
assert.match(page, /report && !actualColumns\.length[\s\S]*선택 범위에 주문이 있는 세부차수가 없습니다/, '7개 선택범위 전체가 empty일 때 안내 카드를 표시한다');
assert.match(page, /mappingWarning/, '저장 공간 제한을 사용자에게 알린다');
assert.match(page, /function ChinaOrderDownloadPage/, '기본 페이지 컴포넌트만 Next 라우트로 노출한다');
assert.doesNotMatch(page, /<Layout|from ['"].*Layout/, '공통 shell에서 중복 Layout을 만들지 않는다');
assert.doesNotMatch(page, /\/api\/(?:shipment|warehouse|stock|estimate)\//, '조회 페이지는 ERP 주문 외 쓰기 기능/API를 호출하지 않는다');

console.log('chinaOrderDownload UI contract passed');
