const assert = require('assert');
const fs = require('fs');
const path = require('path');

const pagePath = path.join(__dirname, '..', 'pages', 'stats', 'china-order-download.js');
const page = fs.readFileSync(pagePath, 'utf8');

assert.match(page, /import \{ apiGet \} from '\.\.\/\.\.\/lib\/useApi'/, '조회는 공통 인증 API 클라이언트를 사용한다');
assert.match(page, /apiGet\('\/api\/stats\/china-order-download', params\)/, '중국 주문 조회 API를 호출한다');
assert.match(page, /selected \? \{ year: selected\.year, majorWeek: selected\.majorWeek \} : \{\}/, '기본 달력 조회는 파라미터를 생략하고 이동 조회는 연도와 대차수를 함께 보낸다');
assert.match(page, /if \(selected && \(Number\(result\.scope\.year\)[\s\S]*요청한 중심 차수와 조회 결과가 다릅니다/, '성공 응답도 요청한 중심 연도·차수와 불일치하면 거부한다');
assert.match(page, /result\.readOnly !== true/, '응답의 읽기 전용 계약을 확인한다');
assert.match(page, /Array\.isArray\(result\.availableCycles\)/, '화면 차수 선택은 서버가 반환한 실제 달력에 한정한다');
assert.match(page, /visibleReport\.cycles\.map/, 'API가 반환한 중심 이전·이후 7개 차수 열을 표시한다');
assert.match(page, /availableCycles\.findIndex[\s\S]*availableCycles\[index \+ delta\]/, '이전/다음은 실제 차수 목록 기준으로 이동한다');
assert.match(page, /matchChinaHfCode\(row, mapping, report\.products \|\| \[\]\)/, '품목별 HF 매칭에 전체 활성 중국 품목을 전달해 고유 fallback을 판별한다');
assert.match(page, /report\.orders\.filter\(order => identities\.has\(productIdentity\(order\)\)\)/, '현재 검색·상태 필터에 해당하는 품목과 단위의 상세 주문만 내보낸다');
assert.ok(/localStorage\.getItem[\s\S]*nextMapping = normalizeHfMapping\(saved\.mapping \|\| saved\)[\s\S]*catch \{[\s\S]*nextMapping = normalizeHfMapping\(seedMapping\)/.test(page), '인증된 사용자의 사전이 있을 때만 복원하고 없으면 기본 사전을 사용한다');
assert.ok(page.indexOf("apiGet('/api/auth/me')") < page.indexOf('localStorage.getItem'), '사용자 인증 확인 후에만 사용자별 브라우저 사전을 읽는다');
assert.match(page, /STORAGE_PREFIX.*encodeURIComponent\(userId\)/, '저장 키는 기능과 인증 사용자 ID로 범위를 격리한다');
assert.match(page, /file\.size > MAX_UPLOAD_BYTES/, '5MiB 초과 파일은 사전을 교체하지 않고 거부한다');
assert.match(page, /const id = \+\+uploadId\.current[\s\S]*id !== uploadId\.current/, '업로드 요청 ID로 오래된 업로드 결과가 최신 상태를 덮지 않는다');
assert.match(page, /normalizeHfMapping\(saved\.mapping \|\| saved\)[\s\S]*catch \{[\s\S]*nextMapping = normalizeHfMapping\(seedMapping\)/, '손상되거나 유효하지 않은 사용자 사전은 인증을 실패시키지 않고 기본 사전으로 복구한다');
assert.match(page, /uploadId\.current \+= 1;[\s\S]*downloadId\.current \+= 1;/, '언마운트 때 진행 중인 업로드·다운로드 응답을 무효화한다');
assert.match(page, /if \(id !== downloadId\.current\) return;/, '언마운트된 다운로드는 브라우저 파일 저장을 시작하지 않는다');
assert.match(page, /if \(id === downloadId\.current\) setDownloading\(false\)/, '언마운트 뒤 다운로드 완료가 상태를 갱신하지 않는다');
assert.match(page, /기존 사전은 그대로 유지했습니다/, '잘못된 업로드는 기존 사전을 보존하고 실패를 설명한다');
assert.match(page, /브라우저 저장은 되지 않았습니다/, '저장 공간 부족 때 화면 적용과 영구 저장 실패를 구분한다');
assert.match(page, /accept="\.xlsx"/, '사전 업로드는 XLSX만 허용한다');
assert.match(page, /await workbook\.xlsx\.writeBuffer\(\)/, 'ExcelJS workbook을 브라우저에서 생성한다');
assert.match(page, /disabled=\{busy \|\| !visibleReport\?\.rows\.length \|\| !isReportCurrent\}/, '로딩·작업중·빈 결과 또는 미조회 차수에서는 다운로드를 차단한다');
assert.match(page, /품목명 또는 HF CODE 검색[\s\S]*disabled=\{!report \|\| busy\}/, '업로드·다운로드 중에는 검색 필터 입력을 잠근다');
assert.match(page, /매칭 상태 필터[\s\S]*disabled=\{!report \|\| busy\}/, '업로드·다운로드 중에는 상태 필터 변경을 잠근다');
assert.match(page, /cycle\.offset === 0 \? 'center-cycle'/, '실제 중심 대차수의 헤더와 수량 열을 은은하게 강조한다');
assert.match(page, /\.orders-table thead \.qty-heading\.center-cycle/, '중심 차수 강조색을 적용한다');
assert.match(page, /const reportCenter = report\?\.cycles\?\.\[3\]/, '조회결과 기준 차수는 API scope dates가 아니라 실제 중심 달력 행을 쓴다');
assert.match(page, /report && !isReportCurrent[\s\S]*중심 차수가 변경됐습니다[\s\S]*이전 결과는 다운로드할 수 없습니다/, '차수 선택 변경 시 재조회 안내를 하고 이전 데이터를 새 차수로 오인시키지 않는다');
assert.match(page, /const id = \+\+requestId\.current[\s\S]*id !== requestId\.current/, '경쟁 조회의 오래된 결과는 폐기한다');
assert.match(page, /setReport\(null\)/, '재조회 시작 시 이전 결과를 내보내기 가능한 상태로 남기지 않는다');
assert.match(page, /role="alert"/, '오류를 보조기술에 알린다');
assert.match(page, /role="status"/, '로딩·빈 결과·상태를 보조기술에 알린다');
assert.match(page, /font-size:14px;font-weight:900;line-height:20px/, '중심 수량을 진한 14px 숫자로 표시한다');
assert.match(page, /\.orders-table \.sticky-product\{position:sticky;left:0/, '품목명 열을 고정한다');
assert.match(page, /\.orders-table tbody tr:hover/, '전체 행 hover 상태를 제공한다');
assert.match(page, /overflow-x:auto/, '좁은 화면에서는 표를 가로 스크롤한다');
assert.match(page, /<tfoot>[\s\S]*visibleReport\.totals\.map/, '단위별 합계를 별도 footer 행으로 표시한다');
assert.match(page, /mappingWarning/, '저장 공간 제한을 사용자에게 알린다');
assert.match(page, /function ChinaOrderDownloadPage/, '기본 페이지 컴포넌트만 Next 라우트로 노출한다');
assert.doesNotMatch(page, /<Layout|from ['"].*Layout/, '공통 shell에서 중복 Layout을 만들지 않는다');
assert.doesNotMatch(page, /\/api\/(?:shipment|warehouse|stock|estimate)\//, '조회 페이지는 ERP 주문 외 쓰기 기능/API를 호출하지 않는다');

console.log('chinaOrderDownload UI contract passed');
