const assert = require('assert');
const fs = require('fs');
const path = require('path');

const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'stats', 'china-volume-board.js'), 'utf8');
const productApi = fs.readFileSync(path.join(__dirname, '..', 'pages', 'api', 'stats', 'china-volume-products.js'), 'utf8');
assert.match(page, /width:76px;min-width:76px;max-width:76px;height:32px;min-height:32px/, '1920 화면에서 업체·품목을 더 많이 보는 고밀도 수량 셀을 고정한다');
assert.match(page, /\.box-badges\{position:absolute/, '박스 배지는 셀 레이아웃 밖의 overlay다');
assert.match(page, /color:#d31616;border:1px solid #e32626/, '박스번호는 빨간 글씨와 빨간 테두리다');
assert.match(page, /draft\.allocations\.map/, '박스별로 독립 수정 입력행을 렌더링한다');
assert.match(page, /엑셀 다운로드/, '인쇄 대신 현재 편집 물량표를 엑셀로 다운로드한다');
assert.match(page, /chinaVolumeProductLabel\(row\.prodName\)/, '화면 품목명은 CHINA 접두어를 제거한 공용 라벨을 사용한다');
assert.match(page, /data-digits=\{digits\}/, '박스번호 자릿수를 배지 폭 정책에 전달한다');
assert.match(page, /flex-wrap:wrap/, '자릿수별 실제 폭의 누적값이 셀 폭을 넘으면 다음 줄로 배치한다');
assert.match(page, /box-badge\[data-digits="1"\]\{width:15px\}/, '고밀도 보기에서 1자리 번호는 가장 좁은 폭을 사용한다');
assert.match(page, /box-badge\[data-digits="2"\]\{width:19px\}/, '고밀도 보기에서 2자리 번호는 중간 폭을 사용한다');
assert.match(page, /box-badge\[data-digits="3"\]\{width:24px\}/, '고밀도 보기에서 3자리 번호는 넓은 폭을 사용한다');
assert.match(page, /font-size:15px;line-height:18px;font-weight:900/, '고밀도 셀에서도 수량을 굵게 표시한다');
assert.match(page, /\.qty\{position:absolute;z-index:5;[^}]*pointer-events:none\}/, '박스번호 확장 레이어가 있어도 패킹 수량은 위 레이어에서 항상 표시한다');
assert.match(page, /order-qty/, '패킹 수량과 다른 전산 주문수량은 비교값으로 함께 표시한다');
assert.match(page, /\.box-badges\{z-index:3;/, '박스번호는 수량보다 아래 표시 레이어를 사용한다');
assert.match(page, /planChinaBoxNeighborAreas/, '박스번호가 사용할 빈 인접 셀을 공용 순수 정책으로 계산한다');
assert.match(page, /summarizeChinaVolumeTotals/, '전체 수량 대조 helper를 화면과 엑셀에 공통 사용한다');
assert.match(page, /주문과 인보이스 수량 일치/, '업로드 검토 단계에는 주문과 인보이스 대조 상태를 표시한다');
assert.match(page, /적용 결과 정상/, '적용 후에는 최종표와 박스 배정 대조 상태를 표시한다');
assert.match(page, /미매칭/, '미매칭 수량과 건수를 표시한다');
assert.match(page, /박스배정/, '박스 배정 합계를 표시한다');
assert.match(page, /수량대조/, '엑셀에 수량대조 시트를 추가한다');
assert.match(page, /window\.confirm/, '불일치가 있는 다운로드는 사용자 확인을 요구한다');
assert.match(page, /area-right/, '오른쪽 빈 셀 확장 표시를 지원한다');
assert.match(page, /area-left/, '왼쪽 빈 셀 확장 표시를 지원한다');
assert.match(page, /area-down/, '아래 빈 셀 확장 표시를 지원한다');
assert.match(page, /area-up/, '위 빈 셀 확장 표시를 지원한다');
assert.match(page, /grid-template-columns:minmax\(0,1fr\) 292px/, '1920 화면에서 물량표 영역을 넓히고 입고원장을 좌우 배치한다');
assert.match(page, /\.page,\.toolbar,main,\.board-wrap,aside\{min-width:0\}/, '넓은 물량표가 grid 최소폭을 밀어 우측 인보이스 영역을 화면 밖으로 보내지 않는다');
assert.match(page, /\/api\/stats\/china-volume-board/, '작업본·입고원장 스냅샷은 중국 전용 API에 저장한다');
assert.match(page, /작업 저장/, '차수별 작업 저장 버튼을 제공한다');
assert.match(page, /const DEFAULT_WEEK = '35-01'/, '기본 조회 차수는 35-01이다');
assert.match(page, /apiGet\('\/api\/stats\/pivot-weeks', \{ orderYear: year, source: 'orders' \}\)/, '중국 물량표도 선택 연도의 실제 주문 입력 차수를 조회한다');
assert.match(page, /availableWeeks\.map/, 'DB 입력 세부차수를 축약하지 않고 선택지로 표시한다');
assert.match(page, /baseIndex - delta/, '이전·다음 이동은 계산한 주차가 아니라 DB 입력 차수 배열을 따른다');
assert.match(page, /aria-label="이전 입력 차수"/, '왼쪽 DB 입력 차수 이동 버튼을 제공한다');
assert.match(page, /aria-label="다음 입력 차수"/, '오른쪽 DB 입력 차수 이동 버튼을 제공한다');
assert.doesNotMatch(page, /stepChinaOrderWeek/, '35-01에서 36-01로 건너뛰는 계산식 차수 이동을 사용하지 않는다');
assert.match(page, /적용: \$\{sourceFileName\}/, '현재 적용된 패킹리스트 파일명을 표시한다');
assert.match(page, /nextRows: matched, nextCells: \{\}[^;]*nextPhase: 'REVIEW'/, '패킹 업로드 직후 전산 물량표를 덮지 않고 매칭 검토 작업본으로 저장한다');
assert.match(page, /packingPhase === 'APPLIED' \? \{ \.\.\.cells, \.\.\.automatic \} : cells/, '수동 매칭 중에는 확정 물량표를 덮지 않는다');
assert.match(page, /nextPhase: 'APPLIED'/, '모든 미매칭을 수정한 뒤 명시적으로 매칭 적용 상태를 저장한다');
assert.match(page, /1\. 전산 물량표 확인/, '전산 물량표→인보이스 대조→미매칭 수정→적용 순서를 안내한다');
assert.match(page, /인보이스·매칭 대조/, '전산 물량표 옆에서 인보이스 원문과 매칭 결과를 동시에 표시한다');
assert.match(page, /전산 업체/, '업체 미매칭도 같은 검토 단계에서 수정한다');
assert.match(page, /disabled=\{!canApplyChinaPackingRows\(packingRows\)/, '미매칭이 남아 있으면 매칭 적용 버튼을 차단한다');
assert.match(page, /인보이스 박스 직접 분배/, '매칭된 인보이스에서 박스를 주문 셀로 직접 분배한다');
assert.match(page, /한 박스를 여러 업체·품목으로 나눌 수 있습니다/, '한 박스 분할 분배 방법을 안내한다');
assert.match(page, /validateChinaPackingDistribution/, '인보이스 원본수량과 분배합계를 공용 정책으로 검증한다');
assert.match(page, /setChinaPackingRowDistributions/, '직접 분배 결과를 패킹 작업본에 저장한다');
assert.match(page, /작업본과 업로드 입고원장 스냅샷을 삭제/, '작업본 삭제가 업로드 원장 스냅샷 삭제를 명시한다');
assert.match(page, /save-mapping/, '중국 품목 수동 매칭을 전용 저장 액션으로 보낸다');
assert.match(page, /\/api\/stats\/china-volume-products/, '선택 차수 피벗에 없는 전산 중국 품목도 읽기 전용 후보에서 찾는다');
assert.match(page, /normalizeChinaText\(search\)/, '품목 검색은 괄호·공백·화종 표기를 정규화한다');
assert.match(page, /mergeChinaProductCandidates/, '현재 차수 품목과 전산 중국 품목 후보를 ProdKey로 안전하게 합친다');
assert.match(productApi, /withAuth/, '중국 품목 후보 조회는 로그인 사용자만 가능하다');
assert.match(productApi, /p\.isDeleted = 0 AND p\.CounName = N'중국'/, '활성 중국 Product만 읽는다');
assert.doesNotMatch(productApi, /\b(?:INSERT|UPDATE|DELETE|MERGE)\b/i, '중국 품목 후보 API는 ERP 원장을 변경하지 않는다');
assert.match(page, /업체·품목 매칭 수정/, '품목·업체 미매칭과 기존 매칭은 즉시 같은 처리 모달을 연다');
assert.match(page, /업체·품목 매칭 수정/, '미매칭과 기존 매칭은 같은 업체·품목 편집창에서 수정한다');
assert.match(page, /매칭 저장 후 박스 분배/, '매칭을 저장한 뒤 해당 인보이스의 박스 분배로 바로 이어진다');
assert.match(page, /rematchChinaPackingRow/, '기존 분배를 남겨 다른 업체로 새는 대신 공용 재매칭 정책으로 초기화한다');
assert.match(page, /InlineReviewPanel/, '누락·초과 확인은 같은 페이지 검토 패널에서 처리한다');
assert.match(page, /extractDays\(customer, '중국'\)/, '거래처 비고의 중국 출고요일을 기존 물량표 기준으로 사용한다');
assert.match(page, /customer\.area \|\| '기타'/, '거래처 지역을 기존 물량표 기준으로 표시한다');
assert.match(page, /appliedOnly: true/, '최종 엑셀은 적용된 인보이스 셀만 출력한다');
assert.match(page, /xlsx-js-style/, '엑셀 다운로드는 웹과 유사한 색상·글꼴 스타일을 지원한다');
assert.match(page, /expectedRowVersion/, '저장·삭제는 작업본 RowVersion을 함께 보내 동시수정을 막는다');
assert.match(page, /STALE_BOARD_VERSION/, '낡은 작업본 저장 충돌은 재조회 안내로 표시한다');
assert.ok(!page.includes('localStorage'), '작업본·입고원장은 브라우저 임시 저장소가 아니라 중국 전용 DB API에만 저장한다');
assert.ok(!page.includes('/api/shipment/'), '웹 물량표 화면은 ERP 출고 쓰기 API를 호출하지 않는다');
console.log('chinaVolumeBoard UI contract passed');

