const assert = require('assert');
const fs = require('fs');

const page = fs.readFileSync('pages/stats/china-volume-board.js', 'utf8');
assert.match(page, /InlineReviewPanel/, '누락·초과 검토는 같은 물량표 페이지의 인라인 패널이어야 합니다.');
assert.match(page, /매칭 품목 현황 확인·변경/, '차수 조회 후 매칭 현황을 확인·변경하는 제목을 표시해야 합니다.');
assert.match(page, /전산 주문수량과 인보이스 수량/, '전산 주문과 인보이스 수량을 쉬운 용어로 비교해야 합니다.');
assert.match(page, /인보이스 품목/, '인보이스 원본 품목명을 표시해야 합니다.');
assert.match(page, /DB 매칭 품목/, 'DB 매칭 품목명을 나란히 표시해야 합니다.');
assert.match(page, /미매칭 인보이스·품목/, '인보이스·품목 미매칭을 같은 패널에 표시해야 합니다.');
assert.match(page, /부족|초과/, '수량 부족·초과 판정을 명확히 표시해야 합니다.');
assert.match(page, /박스 분할·배분/, '검토 패널에서 박스 분할·배분으로 바로 이동해야 합니다.');
assert.match(page, /onMatch\(row\.sourceRow\)/, '정확한 원본 행의 매칭 편집을 열어야 합니다.');
assert.match(page, /onDistribution\(row\.sourceRow\)/, '정확한 원본 행의 분배 편집을 열어야 합니다.');
assert.match(page, /'good' : 'bad'/, '수량 일치 행은 블루, 불일치 행은 레드 상태를 사용해야 합니다.');
assert.match(page, /className="review-row bad"/, '미매칭·불일치 행은 레드 상태를 사용해야 합니다.');
assert.match(page, /#edf6ff/, '블루 일치 배경을 제공해야 합니다.');
assert.match(page, /#fff3f1/, '레드 불일치 배경을 제공해야 합니다.');
assert.doesNotMatch(page, /window\.open\(`\/stats\/china-volume-board-review/, '검토 작업은 새창을 열지 않아야 합니다.');
console.log('china volume board inline review UI contract passed');
