const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

async function main() {
  const { resolveColombiaWeight, resolveCountryWeight, assertInboundWeightUnchanged, hasColombiaInbound } = await import('../lib/customsWeightPolicy.js');
  const { RATE_DEFAULTS, resolveColombiaCustomsAllocation, resolveCountryCustomsTotal, splitColombiaAwbWeight } = await import('../lib/customsForwarding.js');
  const { applyProfitReportColombiaRates } = await import('../lib/profitReportCustomsPolicy.js');
  const { computeColombiaAllocation } = await import('../lib/customsForwardingCalc.js');
  const { buildWeekCheck } = await import('../lib/profitReportWeekCheck.js');
  const { buildProfitReportAudit } = await import('../lib/profitReportAudit.js');
  const saved = Object.freeze({ GW: 3342, CW: 3342, HandlingFee: 33000, ItemCount: 4, Truck1t: 0, Truck2_5t: 0, Truck5t: 1, BakSangRateApplied: 460 });
  const inbound = Object.freeze({ GW: 1420, CW: 3342 });
  const rates = applyProfitReportColombiaRates({ ...RATE_DEFAULTS, BakSangRate: 460, Truck5t: 275000, QuarantinePerItemRate: 10000 });
  const boxQty = { '콜롬비아 장미': 94, '콜롬비아 카네이션': 194, '콜롬비아 알스트로': 0, '콜롬비아 루스커스': 43, '콜롬비아 수국': 19 };
  const options = { orderYear: '2026', orderWeek: '31-01', major: '31', colRow: saved, gwDef: inbound, boxQty, rates, airTotal: 9026.56 };
  const result = resolveColombiaCustomsAllocation(options);
  assert.equal(result.row.GW, 1420); assert.equal(result.row.CW, 3342);
  assert.equal(result.weight.source, 'erp_inbound'); assert.equal(result.weight.basis, 'CBM');
  assert.equal(result.total, 1001200);
  const before = resolveColombiaCustomsAllocation({ ...options, gwDef: null });
  assert.equal(before.total - result.total, 884120);
  assert.equal(before.weight.basis, 'GW');
  assert.ok(Math.abs(Object.values(result.allocation).reduce((sum, value) => sum + value.S, 0) - 9026.56) < 0.00001);
  assert.notEqual(result.allocation['콜롬비아 장미'].S, before.allocation['콜롬비아 장미'].S);
  for (const field of ['HandlingFee', 'ItemCount', 'Truck1t', 'Truck2_5t', 'Truck5t', 'BakSangRateApplied']) assert.equal(result.row[field], saved[field]);
  const preview = computeColombiaAllocation({ ...result.row, HandlingFee: 34000, AirRateUSD: 9026.56 }, boxQty, rates);
  const afterEdit = resolveColombiaCustomsAllocation({ ...options, colRow: { ...saved, HandlingFee: 34000 } });
  assert.deepEqual(preview, afterEdit.allocation, 'fee edit preview and reload use same inbound weight');
  assert.equal(saved.GW, 3342, 'saved evidence is not mutated');
  assert.equal(resolveColombiaWeight(saved, { GW: 1420 }).state, 'missing');
  assert.equal(resolveColombiaWeight(saved, { GW: 1420 }).row.GW, 3342, 'do not mix incomplete pair with saved CW');
  assert.equal(resolveColombiaWeight(saved, { GW: 1420, CW: 1000 }).state, 'invalid');
  assert.equal(resolveColombiaWeight(saved, { GW: 2000, CW: 3000, sources: [{ awbGw: 1420, awbCw: 1000 }] }).state, 'invalid', 'aggregate cannot hide invalid AWB');
  assert.equal(resolveColombiaWeight(null, null).state, 'missing');
  assert.equal(resolveColombiaWeight({ GW: 0, CW: 0 }, null).state, 'missing');
  assert.equal(resolveColombiaWeight(saved, { GW: Infinity, CW: 3342 }).source, 'manual');
  assert.equal(resolveColombiaWeight(saved, { GW: 1420, CW: 1420 }).basis, 'GW');
  const invalid = splitColombiaAwbWeight({ gw: 1420, cw: 1136, restWeight: 1, hydWeight: 0 });
  assert.equal(invalid.rest.GW, 1420); assert.equal(invalid.gwClampedToCw, false);
  const historical = resolveColombiaCustomsAllocation({ ...options, orderWeek: '26-01', major: '26' });
  assert.equal(historical.row.GW, 3342, 'historical scope saved evidence preserved');
  const otherYear = resolveColombiaCustomsAllocation({ ...options, orderYear: '2025', orderWeek: '26-01', major: '26', gwDef: { GW: 500, CW: 500 } });
  assert.equal(otherYear.row.GW, 500, '2026 historical exception does not leak to 2025');
  const country = { GW1: 900, GW2: 0, Customs1: 100, WorldFreight1: 99000, WorldFreight1Manual: 1 };
  const countryResolved = resolveCountryCustomsTotal({ row: country, gwDef: { GW1: 500, GW2: 700 }, rates, category: '중국', orderYear: '2026', major: '31' });
  assert.equal(countryResolved.row.GW1, 500); assert.equal(countryResolved.row.GW2, 0, 'explicit zero preserved');
  assert.equal(countryResolved.row.WorldFreight1, 99000);
  assert.equal(resolveCountryWeight(country, null).row.GW1, 900);
  assert.throws(() => assertInboundWeightUnchanged({ GW: 3342 }, result.row, { GW: 'erp_inbound' }), { code: 'INBOUND_WEIGHT_AUTHORITATIVE' });
  assert.doesNotThrow(() => assertInboundWeightUnchanged({ HandlingFee: 34000 }, result.row, { GW: 'erp_inbound' }));
  assert.doesNotThrow(() => assertInboundWeightUnchanged({ GW: 1420 }, result.row, { GW: 'erp_inbound' }));
  const checkInput = { orderYear: '2026', major: '31', sources: { arrivalPrevCountries: ['콜롬비아'], arrival: [], inbound: [] }, report: { rows: [{ category: '콜롬비아 장미', auto: { Q: 100 }, calc: { R: 1496 }, source: { R: 'kcs_api' } }] } };
  assert.equal(buildWeekCheck(checkInput).rows.length, 0, 'no upload requirement when exact taxable rate exists');
  for (const rate of [0, null]) {
    const missing = buildWeekCheck({ ...checkInput, report: { rows: [{ category: '장미', auto: { Q: 0, S: 100 }, calc: { R: rate }, source: { R: 'kcs_api' } }] } });
    assert.equal(missing.rows[0].status, 'input');
  }
  const audit = buildProfitReportAudit([], { major: '31', orderYear: '2026', colombiaWeeks: [{ orderWeek: '31-01', inbound: true, weightState: 'invalid' }] });
  assert.ok(audit.issues.some((issue) => issue.code === 'CUSTOMS_WEIGHT_INVALID' && issue.severity === 'error'));
  const cwOnly = { GW: 0, CW: 3342 };
  const cwOnlyAudit = buildProfitReportAudit([], { major: '31', orderYear: '2026', colombiaWeeks: [{ orderWeek: '31-01', inbound: hasColombiaInbound({}, cwOnly), weightState: resolveColombiaWeight(saved, cwOnly).state }] });
  assert.ok(cwOnlyAudit.issues.some((issue) => issue.code === 'CUSTOMS_WEIGHT_INVALID'));
  assert.equal(hasColombiaInbound({}, {}, ['31-01'], '31-01'), true);
  assert.equal(hasColombiaInbound({}, {}, [], '31-01'), false);
  const overrideRow = Object.freeze({ category: '콜롬비아 장미', currency: 'USD', auto: Object.freeze({ N: 1, H: 1000, S: 200 }), manual: Object.freeze({ H: 1500, S: 250 }), source: {} });
  const overrideContext = { orderYear: '2026', major: '31', automaticSources: { H: { '콜롬비아 장미': 'saved' }, S: { '콜롬비아 장미': 'auto' } } };
  const overrideIssues = (row, context) => buildProfitReportAudit([row], context).issues.filter(issue => issue.code === 'REPORT_COST_OVERRIDE_DIFF');
  const overrideWarning = overrideIssues(overrideRow, overrideContext)[0];
  assert.equal(overrideWarning.severity, 'warning'); assert.deepEqual(overrideWarning.columns, ['H', 'S']);
  assert.match(overrideWarning.message, /1,500원.*1,000원.*500원/); assert.match(overrideWarning.message, /250USD.*200USD.*50USD/);
  assert.equal(overrideRow.manual.H, 1500); assert.equal(overrideRow.manual.S, 250);
  assert.equal(overrideIssues(overrideRow, { ...overrideContext, major: '26' }).length, 0);
  assert.equal(overrideIssues({ ...overrideRow, confirmed: true }, overrideContext).length, 0);
  assert.equal(overrideIssues(overrideRow, { ...overrideContext, automaticSources: {} }).length, 0);
  assert.equal(overrideIssues(overrideRow, { ...overrideContext, colombiaWeeks: [{ inbound: true, weightState: 'invalid' }] }).length, 0);
  assert.equal(overrideIssues({ ...overrideRow, manual: { H: 1000, S: 200 } }, overrideContext).length, 0);
  const panel = fs.readFileSync(path.join(__dirname, '../components/CustomsClearancePanel.js'), 'utf8');
  assert.ok(!panel.includes('manualVal > 0 ? manualVal : autoVal'), 'rejected inbound must not appear as effective automatic weight');
  const source = fs.readFileSync(path.join(__dirname, '../lib/customsForwarding.js'), 'utf8');
  assert.match(source, /CAST\(wm.OrderYear AS NVARCHAR\(4\)\) = @yr/);
  assert.ok(!source.includes('ISNULL(CAST(wm.OrderYear AS NVARCHAR(4)), @yr) = @yr'));
  const hash = require('../lib/profitReportCalcHash.cjs');
  assert.ok(hash.listFiles(path.join(__dirname, '..')).includes('lib/customsWeightPolicy.js'));
  console.log('customsWeightPolicy: 31-01, before/after, fees, preview, partial/invalid, historical/cross-year, FX and hash passed');
}
main().catch((error) => { console.error(error); process.exit(1); });
