const assert=require('node:assert/strict');
const fs=require('node:fs');

const panel=fs.readFileSync(require.resolve('../components/orders/DistributionBaselinePanel.js'),'utf8');
const ui=fs.readFileSync(require.resolve('../components/orders/DistributionBaselineReconciliation.js'),'utf8');

assert.match(panel,/import DistributionBaselineReconciliation/);
assert.match(panel,/const \[savedRecord,setSavedRecord\] = useState\(null\)/);
assert.match(panel,/setSavedRecord\(null\); setCurrentView\(false\)/);
assert.match(panel,/setSavedRecord\(result\.baseline\)/);
assert.match(panel,/record=\{savedRecord\} selectedWeek=\{week\}/);
assert.match(panel,/sheet&&!currentView/);
assert.match(ui,/\/api\/orders\/distribution-baseline-reconciliation/);
assert.match(ui,/baselineId:record\.id/);
assert.match(ui,/sheetScopes:Object\.create\(null\),keymapBatch:Object\.create\(null\),rowOverrides:Object\.create\(null\),columnOverrides:Object\.create\(null\)/);
assert.match(ui,/rowUnitOverrides:Object\.create\(null\)/);
assert.match(ui,/columnDateOverrides:Object\.create\(null\)/);
assert.match(ui,/columnDateOverrides:setMapValue\(previous\.columnDateOverrides,columnId,shipmentDate\?\{shipmentDate,confirmed:true\}:null\)/);
assert.match(ui,/mapValue\(bindings\.columnDateOverrides,column\.id\)/);
assert.doesNotMatch(ui,/columnDateOverrides:\[\]|columnDateOverrides\.find/);
assert.match(ui,/item=>item\.id===activeSheet/);
assert.match(ui,/item=>\[item\.sheetId,item\]/);
assert.doesNotMatch(ui,/item\.sheetId\|\|item\.id|candidate\.id/);
assert.match(ui,/record\?\.parsed\?\.sheets/);
assert.match(ui,/const sourceRows=sourceSheet\?\.rows\|\|\[\]/);
assert.match(ui,/const sourceColumns=sourceSheet\?\.clients\|\|\[\]/);
assert.match(ui,/전산 현재값 보기/);
assert.match(ui,/원본 keymap 대응표/);
assert.match(ui,/표시된 품목 키를 일괄 확인/);
assert.match(ui,/표시된 거래처 키를 일괄 확인/);
assert.match(ui,/위 품목군 전체를 직접 확인/);
assert.match(ui,/원본 요일별 출고일 지정/);
assert.match(ui,/날짜로 추정하지 않습니다/);
assert.match(ui,/const raw=column\.day\|\|'미정'/);
assert.doesNotMatch(ui,/const raw=column\.sourceDay\|\|'미정'/);
assert.match(ui,/원본 내보내기 단위를 그대로 사용함/);
assert.match(ui,/원본 \{text\(cell\?\.baselineRaw\)\}/);
assert.match(ui,/현재 \{numeric\(cell\?\.erpCurrentQuantity\)\}/);
assert.match(ui,/차이 \{delta\(cell\?\.delta\)\}/);
assert.match(ui,/확인 필요/);
assert.match(ui,/max-height:55vh/);
assert.match(ui,/\.reconcile-scroll th small,\.reconcile-scroll td small\{display:block\}/);
assert.match(ui,/record\.fileName\|\|'보관 기준표'/);
assert.match(ui,/observedAtKst\(result\.observedAt\)/);
assert.match(ui,/timeZone:'Asia\/Seoul'/);
assert.match(ui,/const cellByCoordinate=useMemo\(\(\)=>new Map/);
assert.match(ui,/cellByCoordinate\.get/);
assert.match(ui,/settings-body\{max-height:320px;overflow:auto/);
assert.match(ui,/exception-settings/);
assert.match(ui,/mappingEditor/);
assert.match(ui,/slice\(0,30\)/);
assert.match(ui,/원본 품목 키/);
assert.doesNotMatch(ui,/JSON\.stringify\(issue\)|JSON\.stringify\(result\.unclassifiedCurrent\)|\(sheet\?\.cells\|\|\[\]\)\.find/);
assert.match(ui,/onModeChange\?\.\(true\)/);
assert.doesNotMatch(ui,/localStorage|sessionStorage|\/api\/shipment|matchedAll|canSave|blocker|erpWriteAllowed/);
console.log('distribution baseline reconciliation UI tests passed');
