const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {
  MAX_LIST_ITEMS,
  MAX_REPORT_BYTES,
  DistributionAuditStoreError,
  createDistributionAuditStore,
  saveAudit,
  listAudits,
  getAudit,
} = require('../lib/distributionAuditStore');

function report(overrides = {}) {
  return {
    requests: [{ sourceIdentity: 'message:1', action: 'ADD', qty: 3 }],
    findings: [{ code: 'MATCHED_HISTORY', evidenceCount: 1 }],
    unresolved: [],
    warnings: ['자동 대조는 완료 판정이 아닙니다.'],
    advisoryOnly: true,
    ...overrides,
  };
}

function input(overrides = {}) {
  return {
    year: '2026',
    week: '37-01',
    userId: 'audit-user',
    report: report(),
    ...overrides,
  };
}

async function expectCode(promise, code) {
  await assert.rejects(promise, error => error instanceof DistributionAuditStoreError && error.code === code);
}

async function main() {
  const root = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'distribution-audit-store-'));
  try {
    const saved = await saveAudit(
      { ...input(), id: '../../client-id', createdAt: '2000-01-01T00:00:00.000Z' },
      { root, now: () => new Date('2026-09-10T02:03:04.000Z') },
    );
    assert.match(saved.id, /^[0-9a-f-]{36}$/);
    assert.equal(saved.createdAt, '2026-09-10T02:03:04.000Z', 'createdAt is generated by the server store');
    assert.equal(saved.userId, 'audit-user');
    assert.equal(saved.advisoryOnly, true);
    assert.equal(saved.erpAction, 'NONE');
    assert.deepEqual(saved.report, report());

    const filePath = path.join(root, `${saved.id}.json`);
    const stored = JSON.parse(await fs.promises.readFile(filePath, 'utf8'));
    assert.equal(stored.schemaVersion, 1);
    assert.equal(stored.id, saved.id, 'client supplied ID is ignored');
    assert.equal(stored.createdAt, saved.createdAt, 'client supplied timestamp is ignored');
    if (process.platform !== 'win32') {
      assert.equal((await fs.promises.stat(filePath)).mode & 0o777, 0o600, 'snapshot is private');
    }

    assert.deepEqual(await getAudit({ year: '2026', week: '37-01', id: saved.id }, { root }), saved);
    const firstList = await listAudits({ year: '2026', week: '37-01' }, { root });
    assert.equal(firstList.length, 1);
    assert.equal('report' in firstList[0], false, 'list returns bounded metadata, not the full report');
    assert.deepEqual(firstList[0].counts, { requests: 1, findings: 1, unresolved: 0, warnings: 1 });

    for (let index = 0; index < MAX_LIST_ITEMS + 5; index += 1) {
      await saveAudit(input({ report: report({ findings: [{ index }] }) }), {
        root,
        now: () => new Date(Date.UTC(2026, 8, 10, 3, 0, index)),
      });
    }
    const limited = await listAudits({ year: '2026', week: '37-01' }, { root });
    assert.equal(limited.length, MAX_LIST_ITEMS, 'list is limited to the 20 most recent snapshots');
    assert.ok(limited[0].createdAt > limited.at(-1).createdAt, 'list is newest first');

    await saveAudit(input({ year: '2025' }), { root });
    assert.equal((await listAudits({ year: '2026', week: '37-01' }, { root })).some(row => row.year === '2025'), false, 'same week in another year never leaks');
    await expectCode(getAudit({ year: '2025', week: '37-01', id: saved.id }, { root }), 'AUDIT_NOT_FOUND');
    await expectCode(getAudit({ year: '2026', week: '37-01', id: '../escape' }, { root }), 'INVALID_AUDIT_ID');

    await expectCode(saveAudit(input({ year: '2026 ' }), { root }), 'INVALID_YEAR');
    await expectCode(saveAudit(input({ week: '37' }), { root }), 'INVALID_WEEK');
    await expectCode(saveAudit(input({ week: '00-01' }), { root }), 'INVALID_WEEK');
    await expectCode(saveAudit(input({ week: '54-01' }), { root }), 'INVALID_WEEK');
    await expectCode(saveAudit(input({ week: '37-00' }), { root }), 'INVALID_WEEK');
    const upperBoundary = await saveAudit(input({ week: '53-99' }), { root });
    assert.equal(upperBoundary.week, '53-99', 'major 53 and subweek 99 are accepted');
    await expectCode(saveAudit(input({ userId: '' }), { root }), 'MISSING_USER');
    await expectCode(saveAudit(input({ report: report({ advisoryOnly: false }) }), { root }), 'INVALID_REPORT_SCHEMA');
    await expectCode(saveAudit(input({ report: report({ findings: null }) }), { root }), 'INVALID_REPORT_SCHEMA');
    await expectCode(saveAudit(input({ report: report({ requests: [{ authorization: 'Bearer hidden-value' }] }) }), { root }), 'REPORT_CONTAINS_SECRET');
    await expectCode(saveAudit(input({ report: report({ warnings: [`Bearer ${'x'.repeat(20)}`] }) }), { root }), 'REPORT_CONTAINS_SECRET');
    await expectCode(saveAudit(input({ report: report({ warnings: ['한'.repeat(MAX_REPORT_BYTES)] }) }), { root }), 'REPORT_TOO_LARGE');

    const collisionRoot = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'distribution-audit-collision-'));
    try {
      const collisionId = '550e8400-e29b-41d4-a716-446655440000';
      const collisionStore = createDistributionAuditStore({ root: collisionRoot, randomUUID: () => collisionId });
      const first = await collisionStore.saveAudit(input());
      await expectCode(collisionStore.saveAudit(input({ report: report({ warnings: ['different'] }) })), 'AUDIT_ID_COLLISION');
      assert.deepEqual(await collisionStore.getAudit({ year: '2026', week: '37-01', id: first.id }), first, 'exclusive append never overwrites an existing UUID');
    } finally {
      await fs.promises.rm(collisionRoot, { recursive: true, force: true });
    }

    const corruptRoot = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'distribution-audit-corrupt-'));
    try {
      const corruptId = '550e8400-e29b-41d4-a716-446655440000';
      await fs.promises.writeFile(path.join(corruptRoot, `${corruptId}.json`), '{broken', { flag: 'wx' });
      await expectCode(listAudits({ year: '2026', week: '37-01' }, { root: corruptRoot }), 'AUDIT_STORAGE_CORRUPT');
    } finally {
      await fs.promises.rm(corruptRoot, { recursive: true, force: true });
    }

    const malformedRoot = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'distribution-audit-malformed-'));
    try {
      const malformedId = '550e8400-e29b-41d4-a716-446655440000';
      await fs.promises.writeFile(path.join(malformedRoot, `${malformedId}.json`), JSON.stringify({
        schemaVersion: 1,
        id: malformedId,
        year: '2026',
        week: '37-01',
        userId: '',
        createdAt: '2026-09-10T02:03:04.000Z',
        advisoryOnly: true,
        erpAction: 'NONE',
        report: report(),
      }), { flag: 'wx' });
      await expectCode(getAudit({ year: '2026', week: '37-01', id: malformedId }, { root: malformedRoot }), 'AUDIT_STORAGE_CORRUPT');
    } finally {
      await fs.promises.rm(malformedRoot, { recursive: true, force: true });
    }

    console.log('distribution audit store tests passed');
  } finally {
    await fs.promises.rm(root, { recursive: true, force: true });
  }
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
