const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');

const audit=fs.readFileSync(require.resolve('../components/orders/DistributionChangeAudit.js'),'utf8');
const inbox=fs.readFileSync(require.resolve('../components/orders/DistributionSalesInbox.js'),'utf8');
const auditApi=fs.readFileSync(require.resolve('../pages/api/orders/distribution-change-audit.js'),'utf8');

assert.match(audit,/function shortAuditWeek/);
assert.match(audit,/match\[1\]===String\(year\|\|''\)/);
assert.match(audit,/\/api\/orders\/distribution-change-audit/);
assert.match(audit,/method:'POST'/);
assert.match(audit,/messages\.length>50/);
assert.match(audit,/identity:message\.identity,message:message\.message,created_at:message\.created_at,timestamp_approximate:message\.timestamp_approximate/);
assert.match(audit,/combinedAvailable=shortWeek\?\.endsWith\('-02'\)/);
assert.match(audit,/function alignedFindings/);
assert.match(audit,/audit\.findings\.map\(\(finding,index\)=>\(\{finding,request:audit\.requests\[index\]\|\|null\}\)\)/);
assert.match(audit,/function validReport/);
assert.doesNotMatch(audit,/function validReport\(report\) \{\s*return !!report&&report\.success===true/);
assert.match(audit,/report\.advisoryOnly===true/);
assert.match(audit,/report\.scope/);
assert.match(audit,/data\?\.success!==true\|\|!validReport\(data\)/);
assert.match(audit,/카톡 변경사항 비교/);
assert.match(audit,/선택 \$\{messages\.length\}건 전산 이력과 비교/);
assert.match(audit,/01·02 전산 함께 비교/);
assert.match(audit,/customerText/);assert.match(audit,/productText/);assert.match(audit,/inputQty/);assert.match(audit,/inputUnit/);
assert.match(audit,/요청 차수/);assert.match(audit,/이력 근거/);assert.match(audit,/quoteFor/);
assert.match(audit,/activeContext\.current!==runContext/);
assert.match(audit,/activeContext\.current='unmounted'/);
assert.match(audit,/분석 \{audit\.requests\.length\}건/);
assert.doesNotMatch(audit,/\['참고 항목',audit\.findings\]/);
assert.match(audit,/function candidateEventsFor/);
assert.match(audit,/Array\.isArray\(finding\?\.evidence\?\.candidateEvents\)/);
assert.match(auditApi,/evidence:\s*\{\s*candidateEvents:/);
const candidateEventsFor=vm.runInNewContext(`(${audit.match(/function candidateEventsFor\(finding\) \{[\s\S]*?\n\}/)[0]})`);
const candidateEvent={before:3,after:5,changeAt:'2026-09-10T09:00:00+09:00',week:'31-01',shipmentDate:'2026-09-12',unit:'BOX'};
const canonicalFinding={evidence:{candidateEvents:[candidateEvent]}};
assert.equal(candidateEventsFor(canonicalFinding).length,1);
assert.equal(candidateEventsFor(canonicalFinding)[0],candidateEvent);
assert.equal(candidateEventsFor({candidateEvents:[candidateEvent]}).length,0);
assert.match(audit,/이력 근거 \{candidateEventsFor\(finding\)\.length\}건 보기/);
assert.match(audit,/event\.before\?\?'/);assert.match(audit,/event\.after\?\?'/);assert.match(audit,/event\.changeAt/);
assert.match(audit,/\/api\/orders\/distribution-change-audits\?/);
assert.match(audit,/이전 비교 결과/);
assert.match(audit,/data\.audit\.report/);
assert.match(audit,/저장된 비교 결과/);
assert.doesNotMatch(audit,/localStorage|sessionStorage|parse-paste|handleAllMixedDistribute/);
assert.match(audit,/MATCHING_HISTORY:'동일 변동 이력'/);
assert.match(audit,/PARTIAL_HISTORY:'일부 이력'/);
assert.match(audit,/NEEDS_REVIEW:'확인 필요'/);
assert.match(audit,/실제 적용·완료 여부를 판단하거나 기존 작업을 막지 않습니다/);
assert.match(audit,/수동 검토 상태는 별도 체크리스트에서 관리합니다/);
assert.doesNotMatch(audit,/parse-paste|adjust-batch|handleAllMixedDistribute|\/api\/orders\/index/);
assert.match(inbox,/import DistributionChangeAudit from '\.\/DistributionChangeAudit'/);
assert.match(inbox,/DistributionChecklistReview key=/);
assert.match(inbox,/DistributionChangeAudit key=\{`audit:\$\{year\|\|''\}:\$\{week\|\|''\}`\}/);
assert.match(inbox,/messages=\{rows\.filter\(row=>selected\[row\.identity\]\)\}/);
console.log('distribution change audit UI tests passed');
