const assert=require('node:assert/strict');
const fs=require('node:fs');

const panel=fs.readFileSync(require.resolve('../components/orders/DistributionBaselinePanel.js'),'utf8');
const ui=fs.readFileSync(require.resolve('../components/orders/DistributionBaselineReconciliation.js'),'utf8');
const helperSource=ui.slice(0,ui.indexOf('export default function')).replace(/^import .*?;\r?\n/m,'').replace(/^export /gm,'');
const {createEmptyBindings,pageWindow,acceptsReconciliationResponse}=new Function(`${helperSource};return {createEmptyBindings,pageWindow,acceptsReconciliationResponse};`)();

const emptyBindings=createEmptyBindings();
for(const name of ['sheetScopes','keymapBatch','rowOverrides','columnOverrides','columnDateOverrides','rowUnitOverrides']) {
  assert.equal(Array.isArray(emptyBindings[name]),false,`${name} must begin as an ID map`);
  assert.equal(Object.getPrototypeOf(emptyBindings[name]),null,`${name} must begin as a null-prototype map`);
}
assert.deepEqual(emptyBindings.dateGroups,[]);
const hundredThousand=Array.from({length:100000},(_,index)=>index);
assert.deepEqual(pageWindow(hundredThousand,0,25),{items:hundredThousand.slice(0,25),page:0,pages:4000,total:100000,start:0,end:25});
assert.deepEqual(pageWindow(hundredThousand,99999,20),{items:hundredThousand.slice(99980),page:4999,pages:5000,total:100000,start:99980,end:100000});
assert.equal(acceptsReconciliationResponse({activeScope:'a',requestScope:'a',requestSequence:3,currentSequence:3,requestRevision:5,currentRevision:5}),true);
assert.equal(acceptsReconciliationResponse({activeScope:'a',requestScope:'a',requestSequence:3,currentSequence:4,requestRevision:5,currentRevision:5}),false);
assert.equal(acceptsReconciliationResponse({activeScope:'a',requestScope:'a',requestSequence:3,currentSequence:3,requestRevision:5,currentRevision:6}),false);

assert.match(panel,/import DistributionBaselineReconciliation/);
assert.match(panel,/const \[savedRecord,setSavedRecord\] = useState\(null\)/);
assert.match(panel,/setSavedRecord\(null\); setCurrentView\(false\)/);
assert.match(panel,/setSavedRecord\(result\.baseline\)/);
assert.match(panel,/record=\{savedRecord\} selectedWeek=\{week\}/);
assert.match(panel,/sheet&&!currentView/);
assert.match(ui,/\/api\/orders\/distribution-baseline-reconciliation/);
assert.match(ui,/baselineId:record\.id/);
assert.match(ui,/sheetScopes:Object\.create\(null\),keymapBatch:Object\.create\(null\),rowOverrides:Object\.create\(null\),columnOverrides:Object\.create\(null\)/);
assert.match(ui,/rowUnitOverrides:Object\.create\(null\)/);
assert.match(ui,/columnDateOverrides:Object\.create\(null\)/);
assert.match(ui,/columnDateOverrides:setMapValue\(previous\.columnDateOverrides,columnId,shipmentDate\?\{shipmentDate,confirmed:true\}:null\)/);
assert.match(ui,/mapValue\(bindings\.columnDateOverrides,column\.id\)/);
assert.doesNotMatch(ui,/columnDateOverrides:\[\]|columnDateOverrides\.find/);
assert.match(ui,/item=>item\.id===activeSheet/);
assert.match(ui,/item=>\[item\.sheetId,item\]/);
assert.doesNotMatch(ui,/item\.sheetId\|\|item\.id|candidate\.id/);
assert.match(ui,/record\?\.parsed\?\.sheets/);
assert.match(ui,/const sourceRows=sourceSheet\?\.rows\|\|\[\]/);
assert.match(ui,/const sourceColumns=sourceSheet\?\.clients\|\|\[\]/);
assert.match(ui,/전산 현재값 보기/);
assert.match(ui,/원본 keymap 대응표/);
assert.match(ui,/표시된 품목 키를 일괄 확인/);
assert.match(ui,/표시된 거래처 키를 일괄 확인/);
assert.match(ui,/위 품목군 전체를 직접 확인/);
assert.match(ui,/원본 요일별 출고일 지정/);
assert.match(ui,/날짜로 추정하지 않습니다/);
assert.match(ui,/const raw=column\.day\|\|'미정'/);
assert.doesNotMatch(ui,/const raw=column\.sourceDay\|\|'미정'/);
assert.match(ui,/원본 내보내기 단위를 그대로 사용함/);
assert.match(ui,/원본 \{text\(cell\?\.baselineRaw\)\}/);
assert.match(ui,/현재 \{numeric\(stale\?null:cell\?\.erpCurrentQuantity\)\}/);
assert.match(ui,/차이 \{delta\(stale\?null:cell\?\.delta\)\}/);
assert.match(ui,/확인 필요/);
assert.match(ui,/max-height:55vh/);
assert.match(ui,/\.reconcile-scroll th small,\.reconcile-scroll td small\{display:block\}/);
assert.match(ui,/record\.fileName\|\|'보관 기준표'/);
assert.match(ui,/observedAtKst\(result\.observedAt\)/);
assert.match(ui,/timeZone:'Asia\/Seoul'/);
assert.match(ui,/const cellByCoordinate=useMemo\(\(\)=>new Map/);
assert.match(ui,/cellByCoordinate\.get/);
assert.match(ui,/const ROW_PAGE_SIZE=25/);
assert.match(ui,/const COLUMN_PAGE_SIZE=20/);
assert.match(ui,/const rowWindow=pageWindow\(filteredRows,rowPage,ROW_PAGE_SIZE\)/);
assert.match(ui,/const columnWindow=pageWindow\(sheet\?\.columns\|\|\[\],columnPage,COLUMN_PAGE_SIZE\)/);
assert.match(ui,/rowWindow\.items\.map/);
assert.match(ui,/columnWindow\.items\.map/);
assert.match(ui,/이전 차이값을 숨겼습니다/);
assert.match(ui,/전체 \{sheet\.rows\.length\}품목/);
assert.match(ui,/원본 \{sourceRows\.length\}품목/);
assert.match(ui,/function updateBindings\(update\)/);
assert.match(ui,/bindingRevision\.current\+\+;sequence\.current\+\+/);
assert.match(ui,/acceptsReconciliationResponse\(\{activeScope:activeScope\.current/);
assert.match(ui,/범위 확인 전 전산 후보/);
assert.match(ui,/const \[settingsOpen,setSettingsOpen\]=useState\(true\)/);
assert.match(ui,/successfulLoads\.current>0\)setSettingsOpen\(false\)/);
assert.match(ui,/open=\{settingsOpen\} onToggle=\{event=>setSettingsOpen\(event\.currentTarget\.open\)\}/);
assert.match(ui,/settings-body\{max-height:320px;overflow:auto/);
assert.match(ui,/exception-settings/);
assert.match(ui,/mappingEditor/);
assert.match(ui,/slice\(0,30\)/);
assert.match(ui,/원본 품목 키/);
assert.doesNotMatch(ui,/JSON\.stringify\(issue\)|JSON\.stringify\(result\.unclassifiedCurrent\)|\(sheet\?\.cells\|\|\[\]\)\.find/);
assert.match(ui,/onModeChange\?\.\(true\)/);
assert.doesNotMatch(ui,/localStorage|sessionStorage|\/api\/shipment|matchedAll|canSave|blocker|erpWriteAllowed/);
console.log('distribution baseline reconciliation UI tests passed');
