import assert from 'node:assert/strict';
import fs from 'node:fs';
const page = fs.readFileSync(new URL('../pages/stats/dutch-volume-board.js', import.meta.url), 'utf8');
const volumeSheet = fs.readFileSync(new URL('../components/dutch/DutchVolumeSheet.js', import.meta.url), 'utf8');
const pricing = fs.readFileSync(new URL('../lib/dutchVolumePrice.js', import.meta.url), 'utf8');
const layout = fs.readFileSync(new URL('../components/Layout.js', import.meta.url), 'utf8');
assert.match(layout, /\/stats\/dutch-volume-board[^\n]+네덜란드 물량표/);
assert.doesNotMatch(page, /<Layout|import Layout/);
assert.match(page, /onKeyDown=\{event => moveNext\(event, index\)\}/);
assert.match(page, /className="board-layout"/, '작업을 물량표와 보조 패널로 분리해야 합니다.');
assert.match(page, /className="board-primary" aria-label="네덜란드 물량표"/, '원본 물량표를 왼쪽 주 영역에 우선 배치해야 합니다.');
assert.match(page, /className="board-side" aria-label="보조 기능"/, '작업 이력과 입력 안내를 우측 보조 영역에 배치해야 합니다.');
assert.match(page, /className="source-controls" aria-label="물량표 불러오기"/, '업로드와 차수 조회는 빈 데이터 상태와 관계없이 상단에서 보여야 합니다.');
assert.match(page, /className="always-actions" aria-label="물량표 작업 도구"/, '행 추가·검증 작업 도구는 빈 데이터 안내 위에서도 보여야 합니다.');
assert.ok(page.indexOf('className="source-controls"') < page.indexOf('className="board-layout"'), '입력 조작부는 엔트리 유무와 무관한 물량표 본문 바깥에 있어야 합니다.');
assert.ok(page.indexOf('className="always-actions"') < page.indexOf('{!entries.length && !loading'), '작업 도구는 빈 데이터 조건보다 먼저 렌더되어야 합니다.');
assert.match(page, /aria-label="차수" value=\{week\}/, '차수 선택은 데이터가 없어도 상단에서 계속 접근할 수 있어야 합니다.');
assert.match(page, /className="load" onClick=\{\(\) => loadLive\(year, week\)\}/, '빈 차수에서도 직접 DB 조회를 재시도할 수 있어야 합니다.');
assert.match(page, /disabled=\{workBusy \|\| applying \|\| previewLoading \|\| !entries\.length\}/, '물량이 없는 동안 ERP 검증은 비활성화하되 버튼은 보여야 합니다.');
assert.match(page, /grid-template-columns:minmax\(0,1fr\) 370px/, '1920×1080에서 물량표에 가변 폭을 주고 우측 패널 폭을 제한해야 합니다.');
assert.match(page, /<div className="side-history"><DutchWorkHistory/, '저장 이력은 우측 세로 패널에 있어야 합니다.');
assert.equal((page.match(/<DutchWorkHistory\b/g) || []).length, 1, '작업 저장 이력 UI를 복제하면 안 됩니다.');
assert.match(page, /zoom:\.7;width:142\.8571429%/, '데스크톱 화면은 축소된 기본 배율로 넓은 물량표를 보여야 합니다.');
assert.match(page, /@media\(max-width:1100px\)\{\.dutch-board\{zoom:1;width:100%\}/, '작은 화면에서는 페이지 확대율을 원래대로 복원해야 합니다.');
assert.match(volumeSheet, /data-testid="dutch-volume-top-scroll"/, '가로로 긴 원본 물량표는 상단 가로 이동바를 제공해야 합니다.');
assert.match(volumeSheet, /aria-label="원본 물량표 상단 가로 스크롤"/, '상단 가로 이동바는 스크린 리더에서 구분되어야 합니다.');
assert.match(volumeSheet, /onScroll=\{\(\) => syncHorizontalScroll\(topScrollRef, scrollRef\)\}/, '상단 가로 이동바를 움직이면 원본 표도 같은 위치로 이동해야 합니다.');
assert.match(volumeSheet, /onScroll=\{\(\) => syncHorizontalScroll\(scrollRef, topScrollRef\)\}/, '원본 표를 움직여도 상단 가로 이동바가 따라와야 합니다.');
assert.match(volumeSheet, /className="quantity-edit-trigger"/, '수량이 있거나 비어 있는 원본 품목 셀에는 바로 편집할 수 있는 클릭 영역이 있어야 합니다.');
assert.match(volumeSheet, /createDutchBlankCellEntry\(XLSX, sheet, sheetName, rowIndex, colIndex, layoutVersion, quantityMatrixScope\)/, '빈 고객×품목 교차 셀만 편집 초안으로 만들 수 있어야 합니다.');
assert.match(volumeSheet, /onClick=\{\(\) => beginQuantityEdit\(quantityTarget, !entry\)\}/, '기존 행과 빈 셀 모두 같은 수량 편집기로 연결해야 합니다.');
assert.match(volumeSheet, /\{entry \? formatQty\(entry\.quantity\) : ''\}/, '빈 셀은 비어 있는 상태로 보이며 기존 편집 셀은 최종 수량을 보여야 합니다.');
assert.match(volumeSheet, /onQuantityChange\(current\.entryId, parsed\.quantity, current\.newEntry\)/, '빈 원본 셀은 양수 확정 때에만 새 draft row로 연결해야 합니다.');
assert.match(volumeSheet, /onQuantityChange = \(\) => \{\}/, '원본 셀에서 확정한 수량은 초안 콜백으로 전달해야 합니다.');
assert.match(volumeSheet, /onPriceChange = \(\) => \{\}/, '셀의 원화 입력을 공유 가격 초안으로 즉시 전달해야 합니다.');
assert.match(volumeSheet, /weekdayEditable = rowIndex === 1/, '업체별 요일 행은 별도의 클릭 편집 영역이어야 합니다.');
assert.match(volumeSheet, /onDayChange\(sheetName, current\.key, current\.value\)/, '요일 수정은 업체 셀 주소를 부모 draft로 전달해야 합니다.');
assert.match(page, /onDayChange=\{updateWeekday\}/, '요일 수정은 웹 로컬 workbook 상태에 반영해야 합니다.');
assert.match(page, /writeDutchDraft\(localStorage, storageKey, entries, prices, dayEdits, bulkPriceConfig\)/, '요일·일괄 업체 설정은 로컬 저장본에 보존해야 합니다.');
assert.match(pricing, /export function applyDutchWeekdayEdits/, '엑셀 내보내기용으로 허용된 요일 행만 복사 편집해야 합니다.');
assert.match(volumeSheet, /snapshot: snapshotDutchPriceDraft\(prices, keys\)/, '셀 편집 시작 시 공유 대상 모든 가격 상태를 보관해야 합니다.');
assert.match(volumeSheet, /if \(!commit\) onPriceRestore\(current\.snapshot\)/, 'Escape 취소 시 공유 대상 가격 초안을 원래 상태로 복원해야 합니다.');
assert.match(page, /onPriceRestore=\{restorePriceDraft\}/, '가격 편집 취소 콜백을 부모 draft 상태에 연결해야 합니다.');
assert.match(volumeSheet, /onChange=\{event => onPriceChange\(entry, event\.target\.value\)\}/, '셀 원화 입력은 타이핑 즉시 전체 비주광 공통 초안에 반영해야 합니다.');
assert.match(volumeSheet, /hasPrice\(price\) \? formatQty\(price\) : '단가 입력'/, '물량표 셀에는 단가 숫자만 표시하고 원 기호를 덧붙이지 않아야 합니다.');
assert.doesNotMatch(volumeSheet, /formatQty\(price\)}원/, '단가 수치 뒤에 원 단위를 반복 표시하면 안 됩니다.');
assert.match(volumeSheet, /priceKey\(entry\)/, '셀의 원화 입력은 주광 개별·비주광 통합 가격키를 사용해야 합니다.');
assert.match(volumeSheet, /\.quantity-cell\{padding:0!important;text-align:center\}/, '수량·원화 표시 셀은 여백 없이 가운데 정렬해야 합니다.');
assert.match(volumeSheet, /onBlur=\{\(\) => finishQuantityEdit\(true\)\}/, '셀 수량 입력은 포커스를 벗어나면 초안에 반영되어야 합니다.');
assert.match(volumeSheet, /event\.key === 'Escape'\) \{ event\.preventDefault\(\); finishQuantityEdit\(false\); \}/, 'Escape는 셀 편집을 취소해야 합니다.');
assert.match(volumeSheet, /event\.key === 'Enter'\) \{ event\.preventDefault\(\); finishQuantityEdit\(true, true\); \}/, 'Enter는 검증 가능한 입력만 초안에 반영해야 합니다.');
assert.match(page, /disabled=\{workBusy \|\| applying\} onQuantityChange=\{updateCellQuantity\}/, '기존 수량 수정과 빈 셀 추가 모두 preview를 무효화해야 합니다.');
assert.match(page, /\[\.\.\.previous, \{ \.\.\.newEntry, quantity, quantityHistory \}\]/, '빈 원본 셀 입력은 수정 이력과 함께 동일한 ERP 적용 entries 초안에만 추가해야 합니다.');
assert.match(page, /buildDutchQuantitySummaryValues/, '수량 변경 뒤 화면과 엑셀에 주문 합계를 반영해야 합니다.');
assert.match(volumeSheet, /quantity-history-badge/, '수량 수정 이력이 있는 셀에 작은 표시를 제공해야 합니다.');
assert.match(page, /if \(entry\.added \|\| !entry\.sheetName \|\| !entry\.cellAddress \|\| !copy\.Sheets\[entry\.sheetName\]\) continue/, '빈 원본 셀 초안은 엑셀 저장 시 그 원래 좌표에 기록해야 합니다.');
assert.match(page, /addDutchPriceColumns/);
assert.match(page, /addDutchPriceShapesToXlsx/, '다운로드 XLSX에 실제 단가 도형을 삽입해야 합니다.');
assert.match(pricing, /DUTCH_CUSTOMER_COLUMN_WIDTH = 10/, '네덜란드 업체 열 너비를 통일해야 합니다.');
assert.match(pricing, /DUTCH_CUSTOMER_COLUMN_WIDTH = 10/, '네덜란드 업체 열 너비를 통일해야 합니다.');
assert.match(page, /pivot-volume-excel/);
assert.match(page, /attachDutchLiveCustomerKeys\(XLSXStyled, nextWorkbook, parsed\.entries, activeCustomerKeys\)/, 'DB 직접조회에서만 현재 범위에 포함된 고유 거래처키를 적용해야 합니다.');
assert.doesNotMatch(page, /appendDutchPriceSheet|NL_단가표/, '별도 단가 결과 시트를 만들면 안 됩니다.');
assert.match(page, /localStorage/);
assert.match(page, /file\.name.*file\.size.*file\.lastModified/, '같은 파일명의 다른 작업본 단가가 섞이면 안 됩니다.');
assert.doesNotMatch(page, /XLSX\.write\(workbook/, '원본 workbook을 불필요하게 재직렬화해 스타일과 계산식을 잃으면 안 됩니다.');
assert.doesNotMatch(page, /from 'xlsx'/, '업로드도 xlsx-js-style로 읽어 원본 색상과 셀 서식을 보존해야 합니다.');
assert.match(page, /XLSXStyled\.read\(await file\.arrayBuffer\(\)/, '업로드와 다운로드의 스타일 지원 라이브러리를 통일해야 합니다.');
assert.match(page, /수량.*단가/);
assert.doesNotMatch(page, /단가 열만 추가됩니다/, '다운로드 안내에서 별도 단가 열을 추가한다고 설명하면 안 됩니다.');
assert.doesNotMatch(page, /<small>@ /, '웹 미리보기에도 @ 문자를 표시하면 안 됩니다.');
assert.doesNotMatch(page, /writeFile\(/, '도형 삽입 전 일반 writeFile로 바로 저장하면 안 됩니다.');
assert.match(page, /apiGet\('\/api\/stats\/pivot-data', \{ orderYear: selectedYear, weekStart: selectedWeek, weekEnd: selectedWeek \}\)/, '선택한 연도와 DB 세부차수를 시작·종료 범위에 정확히 전달해야 합니다.');
assert.match(page, /네노바웹 물량 바로 불러오기/);
assert.match(page, /일괄업체 설정 ·/, '단가표에서 일괄 업체 설정에 바로 접근할 수 있어야 합니다.');
assert.match(page, /체크한 업체는 일괄 단가에서 제외/, '설정 화면에서 체크 의미가 제외로 명확해야 합니다.');
assert.match(page, /localStorage\.setItem\(BULK_PRICE_CONFIG_KEY/, '일괄 업체 설정은 작업 간에도 브라우저에 저장해야 합니다.');
assert.match(page, /migrateDutchBulkPriceConfig\(entries, prices, bulkPriceConfig, nextConfig\)/, '설정 변경 때 기존 단가를 안전하게 새 적용범위로 옮겨야 합니다.');
assert.match(page, /dutchPriceKey\(row, bulkPriceConfig\)/, '단가 입력과 표시가 현재 일괄 업체 설정을 따라야 합니다.');
assert.match(page, /match\?\.estUnit \? match\.estUnit : '견적단위: 검증 후 확인'/, '편집 표에는 원 기호 대신 견적단위만 표시해야 합니다.');
assert.match(page, /isDutchBulkPriceCustomer\(row, bulkPriceConfig\)/, '포함 업체만 일괄 단가로 표시해야 합니다.');
assert.match(page, /apiGet\('\/api\/stats\/pivot-weeks', \{ orderYear: year, source: 'orders' \}\)/, '선택 연도의 주문 입력 세부차수 목록을 조회해야 합니다.');
assert.match(page, /\(sourceMode === 'SAVED' && !availableWeeks\.includes\(week\) \? \[week, \.\.\.availableWeeks\] : availableWeeks\)\.map\(recordedWeek/, 'DB 입력 이력은 유지하고 저장본의 현재 차수도 선택지로 보존해야 합니다.');
assert.match(page, /baseIndex - delta/, '이전·다음 버튼은 주차 계산이 아니라 DB 입력 차수 순서를 따라야 합니다.');
assert.doesNotMatch(page, /let major = Number/, '35-01에서 36-01로 앞자리만 건너뛰는 계산 이동을 다시 사용하면 안 됩니다.');
assert.match(volumeSheet, /const widths = \[96, 160, 76\]/, '고정 정보 열도 컴팩트하게 줄여 업체 수량 열을 더 보여야 합니다.');
assert.match(volumeSheet, /widthOf = column => column < stickyCount \? widths\[column\] : 52/, '업체별 수량 셀은 더 좁고 균일해야 합니다.');
assert.match(volumeSheet, /\.sheet-scroll table\{font-size:14px\}/, '좁힌 셀 안에서도 표 글자는 이전보다 커야 합니다.');
assert.match(volumeSheet, /\.quantity-edit-trigger\{min-height:26px;font-size:15px;font-weight:800\}/, '물량 숫자는 축소된 전체 배율에서도 눈에 띄게 보여야 합니다.');
assert.match(volumeSheet, /customer-header-label[\s\S]*customerLines\[0\][\s\S]*customerLines\[1\]/, '업체명과 CL 코드는 업체 열에서 위아래로 표시해야 합니다.');
assert.match(volumeSheet, /productUnmatchedEntry[\s\S]*onMatch\(productUnmatchedEntry, 'product'/, '미매칭 품목 선택은 표 화면을 유지하고 별도 매칭 창을 열어야 합니다.');
assert.match(volumeSheet, /customerUnmatchedEntry[\s\S]*onMatch\(customerUnmatchedEntry, 'customer'/, '미매칭 업체 선택은 표 화면을 유지하고 별도 매칭 창을 열어야 합니다.');
assert.ok(page.indexOf('품목 / 원문') < page.indexOf('ERP 매칭 품목') && page.indexOf('ERP 매칭 품목') < page.indexOf('업체 / 원문') && page.indexOf('업체 / 원문') < page.indexOf('ERP 매칭 업체'), '원본 품목과 매칭 품목, 원본 업체와 매칭 업체를 각각 인접 배치해야 합니다.');
assert.doesNotMatch(volumeSheet, /className="source-link"/, '매칭 성공 상태를 수량 셀마다 반복해 공간을 차지하면 안 됩니다.');
assert.match(volumeSheet, /buildDutchQuantitySummaryValues/, '수량 편집 뒤 행 주문합계와 주문 총합계를 시트에 즉시 반영해야 합니다.');
assert.match(volumeSheet, /quantity-history-badge/, '수정 이력이 있는 수량 셀에 작은 이력 표시를 제공해야 합니다.');
assert.match(volumeSheet, /수량 수정 이력 보기/, '이력 표시를 눌러 수정 내역을 확인할 수 있어야 합니다.');
assert.match(page, /appendDutchQuantityHistory/, '수량 변경 전후와 시각을 작업 데이터에 기록해야 합니다.');
assert.match(page, /matchStatusUsable = validationCurrent \|\| Boolean\(applyResult\?\.failed\)/, '적용 오류 후 초안을 고치기 전까지는 실패한 검증에서 미매칭 위치를 유지해야 합니다.');
assert.match(page, /미매칭 · \{customerName\(row\.sourceCustomer \|\| row\.customer\)\}/, '검토 표에서는 간단히 미매칭과 업체명을 함께 표시해야 합니다.');
assert.match(page, /finalProgress = payload\.progress \|\| null/, '적용 실패 시 최종 서버 작업 로그를 다시 읽어 표시해야 합니다.');
assert.match(page, /수정 후 다시 적용할 때는/, '오류를 수정한 뒤 새 검증을 거쳐 재적용하도록 안내해야 합니다.');
console.log('dutch volume price UI tests passed');
