const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

const menu = read('components/Layout.js');
const route = read('pages/estimate/weekday.js');
const workspace = read('components/WeekdayEstimateWorkspace.js');
const uploadApi = read('pages/api/estimate/weekday-upload-preview.js');
const compareApi = read('pages/api/estimate/weekday-compare.js');
const compareHelper = read('lib/weekdayEstimateCompare.js');
const manifest = JSON.parse(read('docs/contracts/estimate-weekday-workspace.json'));

assert.match(menu, /href:\s*'\/estimate\/weekday',[\s\S]{0,80}labelKey:\s*'주광 견적서'/);
assert.match(route, /<WeekdayEstimateWorkspace\s*\/>/);
assert.match(workspace, /선택 범위 전산 대조/);
assert.match(workspace, /credentials:\s*'include'/);
assert.match(workspace, /ERP 적용 · 준비 중/);
assert.match(workspace, /요일 견적 인쇄 · 준비 중/);
assert.match(workspace, /확인 필요/);
assert.doesNotMatch(workspace, /사용 입고 원본행 \(초안\)|입고 후보 선택만/);
assert.doesNotMatch(workspace, /updatePlan\([^\n]*wdetailKey/);
assert.match(workspace, /입고기록은 변경하지 않으며/);
assert.match(uploadApi, /parseWeekdayEstimateBuffer/);
assert.doesNotMatch(uploadApi, /from .*db/);
assert.match(compareApi, /sm\.OrderYear = @year[\s\S]*sm\.OrderWeek IN/);
assert.match(compareApi, /om\.OrderYear = @year[\s\S]*om\.OrderWeek IN/);
assert.match(compareApi, /sm\.CustKey = @custKey/);
assert.match(compareApi, /sd\.CustKey = sm\.CustKey/);
assert.match(compareApi, /filterWeekdayCompareRows\(orderResult\.recordset, scope\)/);
assert.match(compareHelper, /Number\(row\?\.OrderYear\) === Number\(scope\.year\)/);
assert.match(compareHelper, /scope\.weeks\.includes/);
assert.match(compareHelper, /Number\(row\?\.CustKey\) === Number\(scope\.custKey\)/);
assert.match(compareHelper, /scope\.prodKeys\.includes/);
assert.match(compareApi, /readOnly:\s*true/);
assert.doesNotMatch(compareApi, /\b(?:INSERT|UPDATE|DELETE|MERGE)\s+(?:INTO\s+)?(?:Order|Shipment|Estimate|Stock)/i);
assert.deepEqual(manifest.businessIdentity, ['OrderYear', 'OrderWeek', 'CustKey', 'ProdKey']);
assert.ok(manifest.crossYearFixture.required);
assert.ok(manifest.actions.some((action) => action.name === 'WEEKDAY_ESTIMATE_COMPARE_READ_ONLY'));
console.log('Weekday estimate workspace contract tests passed');
