const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const React = require('react');
const {renderToStaticMarkup} = require('react-dom/server');
const {transformSync} = require('next/dist/build/swc');
const {canPreview,previewReports,filterReports} = require('../lib/executiveReportPreview');
assert.equal(canPreview({preview:'1'},null),false);
assert.equal(canPreview({preview:'1'},{userId:'',accountActive:true}),false);
assert.equal(canPreview({preview:'1'},{userId:'a',accountActive:false}),false);
assert.equal(canPreview({preview:['1']},{userId:'a'}),false);
assert.equal(canPreview({},{userId:'a'}),false);
assert.equal(canPreview({preview:'1'},{userId:'a',accountActive:true}),true);
const rows=previewReports('2026-39',true);
assert.equal(rows.length,10);
assert.equal(new Set(rows.map(x=>x.id)).size,10);
assert.equal(previewReports('2026-39').length,3);
assert.ok(rows.every(x=>x.sample && x.period==='2026-39'));
assert.equal(rows.filter(x=>x.planned).length,7);
assert.deepEqual(previewReports('2025-39',true),[]);
assert.deepEqual(previewReports('39',true),[]);
assert.equal(filterReports(rows,'호텔','').length,2);
assert.equal(filterReports(rows,'전체',' 신라 ').length,1);
assert.equal(filterReports(rows,'매출·이익','신라').length,0);
const filename=path.resolve(__dirname,'../components/executive/ExecutiveReports.js');
const compiled=transformSync(fs.readFileSync(filename,'utf8'),{filename,jsc:{parser:{syntax:'ecmascript',jsx:true},target:'es2022',transform:{react:{runtime:'automatic'}}},module:{type:'commonjs'}}).code;
const loaded=new Module(filename,module);
loaded.filename=filename;
loaded.paths=Module._nodeModulePaths(path.dirname(filename));
const original=loaded.require.bind(loaded);
loaded.require=name=>name.endsWith('.css')?{}:original(name);
loaded._compile(compiled,filename);
const render=preview=>renderToStaticMarkup(React.createElement(loaded.exports.default,{preview}));
const locked=render(false),open=render(true);
assert.match(locked,/접속 준비 중/);
assert.match(locked,/type="password"[^>]*disabled/);
assert.doesNotMatch(locked,/라움 순익계산서/);
assert.match(open,/실제 자료 아님/);
assert.match(open,/라움 순익계산서/);
assert.match(open,/신라 순익계산서/);
assert.match(open,/10개 확장 보기/);
assert.doesNotMatch(open,/download=|\/api\//);
const page=fs.readFileSync(path.resolve(__dirname,'../pages/m/executive.js'),'utf8');
assert.match(page,/verifyReqUser\(req\)/);
assert.match(page,/private, no-store/);
console.log('Executive mobile UI: preview authorization, 3/10 catalog, cross-year isolation, filters and React SSR passed');
