const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Module=require('node:module');
const React=require('react');
const {renderToStaticMarkup}=require('react-dom/server');
const {transformSync}=require('next/dist/build/swc');
const filename=path.resolve(__dirname,'../components/FarmQualityInbox.js');
const source=fs.readFileSync(filename,'utf8');
const acknowledgement=source.match(/const acknowledged=(\{\.\.\.result\.event,Evidence:.*?\});setEvents/)[1];
const acknowledge=new Function('result','images',`return (${acknowledgement});`);
const event={EventKey:'saved-event',Body:'저장한 본문',AuthorName:'담당자',Evidence:[]};
const drafts=[{evidenceKey:'saved-image',fileName:'현장.png'}];
assert.deepEqual(acknowledge({event},drafts),{...event,Evidence:[{EvidenceKey:'saved-image',FileName:'현장.png'}]},'explicit empty server array retains the saved attachment preview and event metadata');
const serverImages=[{EvidenceKey:'server-image',FileName:'서버.png'}];
assert.deepEqual(acknowledge({event:{...event,Evidence:serverImages}},drafts).Evidence,serverImages,'nonempty server evidence takes precedence');
assert.deepEqual(acknowledge({event},[]).Evidence,[],'no attachments remains empty');
let stateOverrides={},stateIndex=0;
const summaryFilename=path.resolve(__dirname,'../lib/farmQualityInboxSummary.js');
const summaryModule=new Module(summaryFilename,module);
summaryModule._compile(transformSync(fs.readFileSync(summaryFilename,'utf8'),{filename:summaryFilename,jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}}).code,summaryFilename);
const compiled=transformSync(source,{filename,jsc:{parser:{syntax:'ecmascript',jsx:true},target:'es2022',transform:{react:{runtime:'automatic'}}},module:{type:'commonjs'}}).code;
const loaded=new Module(filename,module);loaded.filename=filename;loaded.paths=Module._nodeModulePaths(path.dirname(filename));
loaded.require=name=>{
 if(name==='../lib/farmQualityInboxSummary')return summaryModule.exports;
 if(name==='react')return {...React,useEffect(){},useRef(value){return {current:value};},useState(value){const index=stateIndex++;return [Object.hasOwn(stateOverrides,index)?stateOverrides[index]:typeof value==='function'?value():value,()=>{}];}};
 if(name==='../lib/farmQuality')return {QUALITY_STATUSES:{NEW:'요청 필요',CLOSED:'개선 확인',WAITING:'미답변'},QUALITY_KINDS:{COMMENT:'코멘트',REQUEST:'요청',RESPONSE:'답변',APPLY:'개선 적용',CLOSE:'개선 확인'},QUALITY_SIGNAL_KINDS:{UNASSIGNED_ITEM_WEEK:'농장 미지정 품목 반복'}};
 if(name==='../lib/farmQualityEvidence')return {QUALITY_EVIDENCE_MAX_BYTES:10485760,QUALITY_EVIDENCE_MAX_FILES:5};
 if(name.startsWith('../lib/'))return {};
 return require(name);
};
loaded._compile(compiled,filename);
const {default:Inbox,inboxTarget,inboxActive}=loaded.exports;
const virtual={key:'v1:2026:1',revision:'revision',orderYear:2026,inboxKeys:[],cases:[],sourceKeys:[1,2],newSourceKeys:[1,2],sourceCount:2,virtual:true,needsFeedback:true,excluded:false,firstWeek:35,lastWeek:35,patternKinds:['UNASSIGNED_ITEM_WEEK'],sources:[{sourceKey:1,orderWeek:'35-01',farmName:'',productName:'장미',customerName:'고객 가',unit:'송이',quantity:2}],sourceReviewRequired:true,sourceReviewReasons:['농장 미지정'],capabilities:{canComment:true,canManage:true,canExclude:true,canRestore:false}};
const closed={...virtual,key:'closed',virtual:false,newSourceKeys:[],cases:[{caseKey:'c1',title:'기존 기록',status:'CLOSED',version:3,eventCount:2}],inboxKeys:['i1'],exclusionScopes:[{inboxKey:'i1',version:4,caseKeys:['c1'],excluded:false}]};
virtual.sources[0].orderYear=2026;
virtual.sources[0].prodKey=1;
const excluded={...closed,key:'excluded',excluded:true,capabilities:{canComment:false,canManage:false,canExclude:false,canRestore:true}};
const multiple={...closed,key:'composite',cases:[...closed.cases,{caseKey:'c2',title:'두 번째 기록',status:'WAITING',version:7,eventCount:3}],inboxKeys:['i1','i2'],exclusionScopes:[...closed.exclusionScopes,{inboxKey:'i2',version:8,caseKeys:['c2'],excluded:false}]};
const data={canManage:true,cases:[{CaseKey:'c1',SourceKey:1,InboxKey:'i1',Version:3},{CaseKey:'c2',SourceKey:2,InboxKey:'i2',Version:7}],inbox:{items:[virtual,closed,excluded,multiple],counts:{active:3}}};
const render=(overrides={})=>{stateOverrides=overrides;stateIndex=0;return renderToStaticMarkup(React.createElement(Inbox,{data,year:2026,from:1,to:53,onDirty(){},onBusy(){},refresh(){}}));};
assert.deepEqual(inboxTarget(virtual,'',data.cases),{anchorSourceKey:1,inboxKey:undefined,caseKey:undefined,revision:'revision'},'unconfirmed/missing farm can target first inbox event');
assert.throws(()=>inboxTarget(multiple,'',data.cases),/선택/,'multiple histories never select the first silently');
assert.equal(inboxTarget(multiple,'c2',data.cases).inboxKey,'i2');
assert.equal(inboxTarget(multiple,'c2',[]).inboxKey,'i2','scope membership resolves inbox when case full data is absent');
assert.equal(inboxActive(excluded),false);
assert.equal(inboxActive({...excluded,newSourceKeys:[3]}),true,'new sources escape old exclusion');
let html=render();assert.match(html,/농장 미지정 · 1개 품목/);assert.match(html,/요청 전/);assert.doesNotMatch(html,/NEW ·|피드백 이슈로 처리/);
closed.cases[0].recentEvents=[{Body:'이전 코멘트',CreatedAt:'2026-09-14T00:00:00Z'},{Body:'최신 농장 답변 확인',AuthorName:'농장 담당',CreatedAt:'2026-09-15T00:00:00Z'}];
html=render();assert.match(html,/title="최신 농장 답변 확인 · 농장 담당/);assert.match(html,/class="latest-comment"[^>]*>최신 농장 답변 확인<\/span>/);assert.match(html,/농장 담당/);assert.match(html,/2026\. 9\. 15\./);assert.doesNotMatch(html,/>이전 코멘트</);
html=render({0:'NEW'});assert.doesNotMatch(html,/>기존 기록 · 개선 확인/,'CLOSED with no new sources is not feedback-needed despite needsFeedback=true');
closed.newSourceKeys=[3];
html=render({0:'NEW'});assert.doesNotMatch(html,/최신 농장 답변 확인/,'new sources must not turn CLOSED or WAITING into NEW');
html=render({0:'CLOSED'});assert.match(html,/class="status-CLOSED">완료</);assert.match(html,/새 불량 1/,'new-source badge is separate from persisted state');
closed.newSourceKeys=[];
html=render();assert.doesNotMatch(html,/농장 미지정 품목 반복/,'raw pattern labels stay inside details');assert.doesNotMatch(html,/>기존 기록 ·/,'case titles do not repeat in compact rows');
const savedItems=data.inbox.items;
const ranked={...virtual,key:'ranked',sources:[1,2,3,4].map(n=>({...virtual.sources[0],sourceKey:n,prodKey:n,farmName:'테스트 농장',flowerName:'장미류',productName:`품목${n}`,quantity:n,orderWeek:'35-01'}))};
ranked.sources.push({...ranked.sources[0],sourceKey:5,prodKey:5,productName:'박스 품목',unit:'박스',quantity:20});
data.inbox.items=[ranked];
html=render();assert.match(html,/테스트 농장 · 장미류/);assert.match(html,/40%/);assert.match(html,/100%/);assert.doesNotMatch(html,/\(불량수량 비중\)/);assert.match(html,/외 1개 품목/);assert.doesNotMatch(html,/>품목1</);assert.match(html,/35차 4/);assert.equal((html.match(/>테스트 농장 · 장미류</g)||[]).length,1);
assert.match(html,/summary-column[\s\S]*badges workflow[\s\S]*products-column/);assert.doesNotMatch(html,/class="progress-column"/);
html=render({2:ranked});const aside=html.slice(html.indexOf('<aside>'));assert.match(aside,/>품목1 · 1 송이</);assert.equal((aside.match(/테스트 농장 · 장미류/g)||[]).length,1);assert.match(aside,/자동 발송되지 않음/);
const sortedItem=(key,lastWeek,status)=>({...ranked,key,lastWeek,cases:[{caseKey:key,status,recentEvents:[{Body:`정렬-${key}`}]}]});
data.inbox.items=[sortedItem('closed',53,'CLOSED'),sortedItem('b',40,'NEW'),sortedItem('a',40,'NEW'),sortedItem('old',39,'NEW'),sortedItem('waiting',52,'WAITING')];
html=render();const offsets=['a','b','old','waiting'].map(key=>html.indexOf(`title="정렬-${key} ·`));assert(offsets.every((offset,index)=>offset>=0&&(!index||offset>offsets[index-1])),'lane order then descending latest week then stable key');
assert.doesNotMatch(html,/title="정렬-closed/);assert.match(html,/그 외 상태 1개/);
assert.equal((html.match(/class="board-column column-/g)||[]).length,4);
for(const code of ['NEW','WAITING','ANSWERED','RECURRED'])assert(html.includes(`board-column column-${code}`));
html=render({0:'CLOSED'});assert.match(html,/title="정렬-closed/);assert.equal((html.match(/class="board-column column-/g)||[]).length,1);
data.inbox.items=[sortedItem('recurrence',40,'RECURRED')];html=render();assert.match(html,/column-RECURRED[\s\S]*title="정렬-recurrence/);
assert.equal((html.match(/해당 상태의 피드백이 없습니다/g)||[]).length,3);
data.inbox.items=savedItems;
for(const lane of ['WAITING','ANSWERED','RECURRED']){html=render({0:lane});if(lane==='WAITING')assert.match(html,/row comment-first/);}
html=render({0:'NEW'});assert.doesNotMatch(html,/class="row comment-first/);
const requestHistory=[{EventKey:1,Kind:'REQUEST',Body:'최초 실제 요청',AuthorName:'요청자'},{EventKey:2,Kind:'RESPONSE',Body:'첫 답변'},{EventKey:3,Kind:'REQUEST',Body:'최근 실제 재요청',AuthorName:'재요청자',DueDate:'2026-09-20'},{EventKey:4,Kind:'COMMENT',Body:'후속 메모1'},{EventKey:5,Kind:'COMMENT',Body:'후속 메모2'},{EventKey:6,Kind:'COMMENT',Body:'후속 메모3'}];
html=render({2:closed,3:'c1',10:requestHistory});let requestPanel=html.slice(html.indexOf('class="saved-request"'),html.indexOf('</section>',html.indexOf('class="saved-request"')));
assert.match(requestPanel,/최근 실제 재요청/);assert.doesNotMatch(requestPanel,/최초 실제 요청|후속 메모|주요 불량 품목의/);assert.match(requestPanel,/재요청자/);assert.match(requestPanel,/2026-09-20/);
html=render({2:closed,3:'c1',10:requestHistory,11:true});requestPanel=html.slice(html.indexOf('class="saved-request"'),html.indexOf('</section>',html.indexOf('class="saved-request"')));assert.match(requestPanel,/불러오는 중/);assert.doesNotMatch(requestPanel,/최근 실제 재요청/);
html=render({2:closed,3:'c1',12:'조회 실패'});assert.match(html,/요청 내용을 불러오지 못했습니다/);
html=render({2:closed,3:'c1',10:[{Kind:'COMMENT',Body:'요청 아닌 일반 메모'}]});requestPanel=html.slice(html.indexOf('class="saved-request"'),html.indexOf('</section>',html.indexOf('class="saved-request"')));assert.match(requestPanel,/아직 저장된 요청이 없습니다/);assert.doesNotMatch(requestPanel,/요청 아닌 일반 메모/);
html=render({2:virtual});assert.match(html,/value="REQUEST"/,'first request available to manager');assert.doesNotMatch(html,/value="RESPONSE"/,'first response is not valid');assert.match(html,/고객 가/);
for(const quantity of [null,undefined,NaN,Infinity]){html=render({2:{...virtual,sources:[{...virtual.sources[0],quantity}]}});assert.match(html,/수량 확인 불가/,'unknown source quantity must not become zero');}
html=render({2:{...virtual,sources:[{...virtual.sources[0],quantity:0}]}});assert.match(html,/0 송이/,'a known zero remains zero');
html=render({2:multiple});assert.match(html,/대상을 직접 선택/);assert.match(html,/두 번째 기록/);assert.match(html,/기록 대상 이력/);assert.match(html,/이력 2/);assert.doesNotMatch(html,/#c2/,'case identity stays in option values only');
html=render({2:excluded,3:'c1'});assert.match(html,/사유를 남기고 복원/,'manager can restore even when event management capability is false');
html=render({2:closed,3:'c1',10:[{EventKey:'e',Kind:'EXCLUDE',Body:'점검',AuthorName:'담당자'}]});assert.match(html,/제외 · 담당자/);assert.doesNotMatch(html,/>EXCLUDE/);
for(const token of ['caseVersion,inboxVersion','inboxExclude','inboxRestore','if(dirty){if(!window.confirm','입력 내용과 첨부 이미지는 유지됩니다.','setMessage(result.replayed','@media(max-width:760px)','height:calc(100vh - 248px)'])assert(source.includes(token),token);
const page=fs.readFileSync(path.resolve(__dirname,'../pages/sales/farm-quality.js'),'utf8');
assert.match(page,/useState\('inbox'\)/);
assert.match(page,/<div hidden=\{tab!=='inbox'\}>/,'tab switches preserve mounted inbox drafts');
const nav=page.match(/<nav>.*?<\/nav>/)[0];assert.equal((nav.match(/<button/g)||[]).length,2,'one unified feedback tab plus analysis');
transformSync(page,{filename:'farm-quality.js',jsc:{parser:{syntax:'ecmascript',jsx:true},target:'es2022'},module:{type:'commonjs'}});
for(const selected of [virtual,closed,multiple])for(const filter of ['ALL','NEW','WAITING','ANSWERED','RECURRED']){
 const detail=render({0:filter,2:selected,3:selected===closed?'c1':''}).split('<aside>')[1].split('</aside>')[0];
 const positions=['class="request-suggestion"','<legend>피드백 기록</legend>','class="saved-request"','class="events"','class="full-products"','원본 근거'].map(token=>detail.indexOf(token));
 assert(positions.every((value,index)=>value>=0&&(!index||value>positions[index-1])),'suggestion and composer precede history and expanded evidence in all entry states');
 const disclosures=detail.match(/<details[^>]*>/g)||[];assert.equal(disclosures.length,3);assert(disclosures.every(tag=>tag.includes('open=""')),'all detail disclosures default open');
 assert.equal(detail.split('<legend>피드백 기록</legend>').length-1,1,'one composer retains existing handlers');
}
assert(source.includes('<aside key={selected.key}>'),'switching cards resets detail scroll and disclosure DOM');
console.log('Farm inbox UI: render, target conflicts, new-source exclusion, manager restore, first kinds, preserved drafts and responsive contracts passed');
