const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.resolve(__dirname, '../pages/sales/farm-quality.js'), 'utf8');
assert.match(source, /\.quality\{color:#19304f/, 'original base layout is retained');
assert.equal((source.match(/<style jsx>/g)||[]).length, 1, 'one styled-jsx scope');
assert.match(source, /\.case-list,\.with-detail \.case-list\{grid-template-columns:1fr;gap:4px/, 'compact full-width rows');
assert.match(source, /clamp\(400px,28vw,440px\)/, 'readable bounded detail pane');
assert.match(source, /grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/, 'three recent events share a row');
assert.match(source, /\.composer textarea\{height:60px/, 'compact editable composer');
assert.match(source, /@media\(max-width:900px\)/, 'narrow layout stacks');
assert.match(source, /latestEvents\(c.RecentEvents\)\.map/, 'sort only presentation');
assert.ok(source.includes('className="case-status">{labels[qualityStatus(c,today())]'), 'status is text, not color only');
assert.ok(source.includes("{c.CreatedByName}{' · '}"), 'metadata has a visible separator');
assert.match(source, /if\(id===sequence.current\)setData\(d\)/, 'load handler preserves original data');
for(const token of ['onClick={()=>open(c)}','onClick={removeCase}','onClick={save}','uploadEvidence','evidenceUrl','title={e.Body}']) assert.ok(source.includes(token), 'preserve '+token);
const expression=source.match(/const latestEvents=(.*);/)[1];
const latest=vm.runInNewContext('('+expression+')');
const fixture=[{EventNo:2},{EventNo:41},{EventNo:7},{EventNo:18}];
assert.equal(JSON.stringify(latest(fixture).map(e=>e.EventNo)), '[41,18,7]');
assert.equal(JSON.stringify(fixture.map(e=>e.EventNo)), '[2,41,7,18]', 'do not mutate source');
assert.equal(latest([]).length,0);
assert.equal(latest(undefined).length,0);
assert.ok(!source.includes('.case-events>small{display:none}'), 'older history count stays visible');
console.log('Farm quality compact UI tests passed: base styles, density, latest 3, immutable data, handlers, responsive layout');
