import assert from 'node:assert/strict';
import fs from 'node:fs';
import {assertQualityRequestEditor,projectQualityRequestEvents} from '../lib/farmQualityRequest.js';
const request={EventKey:'1',Kind:'REQUEST',Body:'original',AuthorId:'Owner',EventDate:'2026-09-14',DueDate:'2026-09-20'};
assertQualityRequestEditor(request,'Owner');
for(const user of ['owner','Owner ','nenovaSS3',undefined,''])assert.throws(()=>assertQualityRequestEditor(request,user),e=>e.code==='INBOX_FORBIDDEN');
assert.throws(()=>assertQualityRequestEditor({...request,Kind:'COMMENT'},'Owner'),e=>e.code==='INBOX_INVALID');
assert.throws(()=>assertQualityRequestEditor(null,'Owner'),e=>e.code==='INBOX_INVALID');
const events=[request,{EventKey:'9007199254740993',Kind:'REQUEST_EDIT',RequestEventKey:'1',Body:'latest'},{EventKey:'9007199254740992',Kind:'REQUEST_EDIT',RequestEventKey:'1',Body:'earlier'}];
const before=structuredClone(events),projected=projectQualityRequestEvents(events,'Owner');
assert.deepEqual(events,before);assert.equal(projected[0].Body,'latest');assert.equal(projected[0].OriginalBody,'original');assert.equal(projected[0].RequestEdited,true);assert.equal(projected[0].CanEditRequest,true);
assert.equal(projected[1].Body,'latest');assert.equal(projected[2].Body,'earlier');assert.equal(projected[1].CanEditRequest,false);
assert.equal(projected[0].EventDate,request.EventDate);assert.equal(projected[0].DueDate,request.DueDate);
assert.equal(projectQualityRequestEvents(events,'other')[0].CanEditRequest,false);
assert.equal(projectQualityRequestEvents([request])[0].RequestEdited,false);
assert.deepEqual(projectQualityRequestEvents(projected,'Owner'),projected);
const scopedRequest={...request,CaseKey:'CASE-A'};
const scopedEdit={EventKey:'2',Kind:'REQUEST_EDIT',RequestEventKey:'1',Body:'same case',CaseKey:'case-a'};
const unrelated={...scopedEdit,EventKey:'3',CaseKey:'case-b',Body:'unrelated'};
assert.equal(projectQualityRequestEvents([scopedRequest,scopedEdit,unrelated],'Owner')[0].Body,'same case');
assert.equal(projectQualityRequestEvents([scopedRequest,unrelated],'Owner')[0].Body,'original');
assert.equal(projectQualityRequestEvents([request,scopedEdit],'Owner')[0].Body,'original');
assert.equal(projectQualityRequestEvents([scopedRequest,{...scopedEdit,CaseKey:undefined}],'Owner')[0].Body,'original');
// Execute the actual GET projection without a database (including old-schema rows).
const store=fs.readFileSync('lib/farmQualityStore.js','utf8');
const getCode=store.slice(store.indexOf('export async function qualityEvents'),store.indexOf('export async function deleteQualityCase')).replace('export async function','async function');
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
let rows=events.map(e=>({...e,PayloadHash:'private hash',RequestKey:'private id'}));
const get=await new AsyncFunction('uuid','qualityScope','ready','query','uid','num','projectQualityRequestEvents',getCode+';return qualityEvents;')(/.*/,({year})=>({year}),async()=>{},async sql=>({recordset:sql.includes('SELECT e.*')?rows:[]}),v=>v,v=>v,projectQualityRequestEvents);
const history=await get('case',2026,{userId:'Owner'});
assert.equal(history[0].Body,'latest');assert.equal(history[0].CanEditRequest,true);
for(const e of history)for(const privateKey of ['PayloadHash','RequestKey','AuthorId'])assert.equal(privateKey in e,false);
assert.equal((await get('case',2026,{userId:'other'}))[0].CanEditRequest,false);
rows=[request];assert.equal((await get('case',2026))[0].RequestEventKey,null);
console.log('Quality request projection and exact editor identity passed');
