import assert from 'node:assert/strict';
import {buildQualityInbox,resolveQualityInboxTarget,qualityInboxMutationPolicy} from '../lib/farmQualityInbox.js';
const scope={year:2026,from:1,to:53};
const source=k=>({DeductionKey:k,OrderYear:2026,OrderWeek:'12',ProdKey:1,ProductName:'장미',FarmName:'',Quantity:2,SourceUnit:k===3?'송이':'박스',CustKey:999777,CustName:'업체',ImportConfirmed:false});
const signal=(kind,keys)=>({kind,sourceKeys:keys,reviewReasons:['농장 미지정 원본 포함']});
const base={scope,sources:[source(1),source(2),source(3),source(4)],signals:[signal('A',[1,2]),signal('B',[2,3]),signal('A',[4])],inboxes:[],links:[],cases:[]};
const before=structuredClone(base),built=buildQualityInbox(base);
assert.equal(built.items.length,2);assert.equal(built.counts.detectedSourceCount,4);
const first=built.items.find(i=>i.sourceCount===3);
assert.deepEqual(first.sourceKeys,[1,2,3]);assert.deepEqual(first.patternKinds,['A','B']);
assert.deepEqual(first.quantitiesByUnit,[{unit:'박스',quantity:4},{unit:'송이',quantity:2}]);
assert.equal(first.key,'v1:2026:1');assert(first.needsFeedback);
assert.equal(buildQualityInbox({...base,sources:[{...source(1),OrderYear:2025},...base.sources]}).items.find(i=>i.key===first.key).revision,first.revision);
assert.deepEqual(base,before);assert(!JSON.stringify(built).includes('CustKey'));assert(!JSON.stringify(built).includes('999777'));
const reordered=buildQualityInbox({...base,scope:{...scope,from:30,to:40},sources:[...base.sources].reverse(),signals:[...base.signals].reverse()});
assert.equal(reordered.items.find(i=>i.sourceCount===3).revision,first.revision);
const target={anchorSourceKey:1,revision:first.revision};
assert.equal(resolveQualityInboxTarget({...base,target}).component.key,first.key);
assert.throws(()=>resolveQualityInboxTarget({...base,target:{...target,revision:'stale'}}),e=>e.code==='INBOX_STALE');
assert.throws(()=>resolveQualityInboxTarget({...base,target:{...target,inboxKey:'wrong'}}),e=>e.code==='INBOX_NOT_FOUND');
const inboxKey='11111111-1111-4111-8111-111111111111',caseKey='22222222-2222-4222-8222-222222222222';
const persisted={...base,inboxes:[{InboxKey:inboxKey,OrderYear:2026,Version:1,Excluded:1,ExclusionReason:'검토 완료'}],links:[1,2].map(SourceKey=>({SourceKey,OrderYear:2026,InboxKey:inboxKey})),cases:[{CaseKey:caseKey,OrderYear:2026,SourceKey:1,InboxKey:inboxKey,Status:'CLOSED',Version:2}]};
const grown=buildQualityInbox(persisted).items.find(i=>i.inboxKeys.length);
assert.deepEqual(grown.newSourceKeys,[3]);assert(!grown.excluded);assert(grown.suspectedRecurrence);
const acknowledgedGrowth={...persisted,inboxes:persisted.inboxes.map(i=>({...i,ExcludedAt:'2026-09-14T00:00:00Z'})),links:[...persisted.links,{SourceKey:3,OrderYear:2026,InboxKey:inboxKey,LinkedAt:'2026-09-15T00:00:00Z'}]};
assert(!buildQualityInbox(acknowledgedGrowth).items.find(i=>i.inboxKeys.length).excluded,'acknowledging new evidence cannot reapply an older exclusion snapshot');
const legacy={...base,signals:[signal('A',[1])],cases:[{CaseKey:caseKey,OrderYear:2026,SourceKey:1,Status:'CLOSED',Version:1}]};
assert(!buildQualityInbox(legacy).items[0].suspectedRecurrence);
assert.deepEqual(resolveQualityInboxTarget({...legacy,target:{anchorSourceKey:1,revision:buildQualityInbox(legacy).items[0].revision}}).newSourceKeys,[1]);
const histories={...persisted,cases:[...persisted.cases,{CaseKey:'33333333-3333-4333-8333-333333333333',OrderYear:2026,SourceKey:2,Status:'WAITING',Version:1}]};
const conflict=buildQualityInbox(histories).items.find(i=>i.caseKeys.length===2);
assert.equal(conflict.conflict,'MULTIPLE_HISTORIES');
const secondInbox='44444444-4444-4444-8444-444444444444';
const bridge={...persisted,inboxes:[...persisted.inboxes,{InboxKey:secondInbox,OrderYear:2026,Version:1,Excluded:0}],links:[...persisted.links,{OrderYear:2026,SourceKey:3,InboxKey:secondInbox}],cases:[...persisted.cases,{CaseKey:'55555555-5555-4555-8555-555555555555',OrderYear:2026,SourceKey:3,InboxKey:secondInbox,Status:'WAITING',Version:1}]};
const composite=buildQualityInbox(bridge).items.find(i=>i.inboxKeys.length===2);
assert.equal(composite.caseKeys.length,2);assert.deepEqual(composite.cases.map(c=>c.status).sort(),['CLOSED','WAITING']);
assert.throws(()=>resolveQualityInboxTarget({...bridge,target:{anchorSourceKey:1,revision:composite.revision}}),e=>e.code==='INBOX_TARGET_REQUIRED');
assert.throws(()=>resolveQualityInboxTarget({...histories,target:{anchorSourceKey:1,revision:conflict.revision}}),e=>e.code==='INBOX_TARGET_REQUIRED');
assert(buildQualityInbox({...persisted,signals:[],sources:[]}).items.some(i=>i.caseKeys.includes(caseKey)));
const sales={userId:'sales',deptName:'영업부'},incoming={userId:'incoming',deptName:'수입부'};
assert.equal(qualityInboxMutationPolicy({action:'event',user:sales,item:first,kind:'COMMENT'}).kind,'COMMENT');
assert.throws(()=>qualityInboxMutationPolicy({action:'exclude',user:sales,reason:'제외'}),e=>e.code==='INBOX_FORBIDDEN');
assert.throws(()=>qualityInboxMutationPolicy({action:'restore',user:incoming,reason:' '}));
assert.equal(qualityInboxMutationPolicy({action:'event',user:incoming,item:first,kind:'REQUEST'}).manage,true);
for(const user of [sales,incoming,{userId:'support',deptName:'영업지원부'}]){
 assert.equal(qualityInboxMutationPolicy({action:'event',user,item:first,kind:'REQUEST'}).kind,'REQUEST');
}
assert.equal(qualityInboxMutationPolicy({action:'event',user:sales,item:{excluded:true},kind:'REQUEST_EDIT'}).kind,'REQUEST_EDIT');
assert.throws(()=>qualityInboxMutationPolicy({action:'event',user:sales,kind:'RESPONSE'}),e=>e.code==='INBOX_FORBIDDEN');
console.log('Farm inbox pure: overlap, stable identity, legacy acknowledgement, conflict and policy passed');
