const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'docs/migrations/2026-10-08_web_invoice_storage_v1.sql'), 'utf8');
const sql = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/--[^\r\n]*/g, '');
const tables = ['WebInvoiceDocument', 'WebInvoiceLine', 'WebInvoiceOperation', 'WebInvoiceHistory', 'WebInvoiceCostRevision', 'WebInvoiceCostLine'];
for (const table of tables) assert.match(sql, new RegExp(`CREATE\\s+TABLE\\s+(?:dbo\\.)?\\[?${table}\\]?\\s*\\(`, 'i'), table);
assert.equal((sql.match(/CREATE\s+TABLE\s+dbo\./gi) || []).length, 6, 'exactly six web tables');
assert.doesNotMatch(sql, /(?:CREATE\s+(?:OR\s+ALTER\s+)?|ALTER\s+)(?:PROCEDURE|TRIGGER|VIEW)\b/i, 'schema preparation cannot alter EXE behavior');
const existing = '(?:WarehouseMaster|WarehouseDetail|TempWarehouseDetail|Product|StockHistory|StockMaster|ProductStock|KeyNumbering|NenovaStockWeekGate|FreightCost|FreightCostDetail|WebArrivalCostLine|OrderMaster|OrderDetail|ShipmentMaster|ShipmentDetail|Estimate|WebProfitReport)';
assert.doesNotMatch(sql, new RegExp(`(?:ALTER\\s+TABLE|DROP\\s+TABLE|TRUNCATE\\s+TABLE|UPDATE|INSERT\\s+(?:INTO\\s+)?|DELETE\\s+(?:FROM\\s+)?)\\s+(?:dbo\\.)?\\[?${existing}\\]?\\b`, 'i'), 'existing ERP tables must remain untouched');
assert.doesNotMatch(sql, /EXEC(?:UTE)?\s+(?:dbo\.)?usp_(?:CreateWarehouse|GetNextKey|StockCalculation|NenovaStockWeekGate)/i, 'migration must not execute stock/numbering procedures');
assert.doesNotMatch(sql, /ON\s+DELETE\s+CASCADE/i, 'historical data cannot cascade-delete');
assert.match(sql, /XACT_ABORT\s+ON/i);
assert.match(sql, /LOCK_TIMEOUT/i);
assert.match(sql, /@@TRANCOUNT/);
assert.match(sql, /nenova1_nenova/);
assert.match(sql, /NenovaInvoiceFixture/);
assert.match(sql, /ROLLBACK/i);
assert.match(sql, /BusinessKeyHash/);
assert.match(sql, /RequestHash/);
assert.match(sql, /EXPECTED_95/);
assert.match(sql, /ACTUAL/);
assert.match(sql, /NenovaWebInvoiceV1CheckHash/);
assert.match(sql, /fingerprints\.value IS NULL/i, 'NULL baseline must not pass SQL three-valued comparison');
assert.match(sql, /indexes\.ignore_dup_key\s*=\s*1/i, 'duplicate writes must fail, not silently disappear');
assert.doesNotMatch(sql, /sp_updateextendedproperty/i, 'rerun cannot bless a changed CHECK definition');
assert.match(sql, /EXEC sys\.sp_executesql @CreateSql/i, 'defer CREATE compilation until partial-schema preflight passes');
const fixture = fs.readFileSync(path.join(root, 'scripts/test-invoice-web-storage-sql.cjs'), 'utf8');
assert.match(fixture, /127\.0\.0\.1/);
assert.match(fixture, /14339/);
assert.match(fixture, /NenovaInvoiceFixture/);
assert.doesNotMatch(fixture, /dotenv/);
console.log('Invoice web storage source boundary checks passed (not a substitute for actual SQL fixture).');
