const assert=require('node:assert/strict');
const {monthlyDemoWeeks}=require('../lib/mobileMonthlyDemo');
const {buildMonthlyProfitSummary}=require('../lib/profitReportMonthly');
const weeks=monthlyDemoWeeks('2026');
const result=buildMonthlyProfitSummary(weeks,'2026');
assert.equal(result.months.length,12);
assert.equal(result.months[8].totals.C,240800000);
assert.equal(result.months[8].totals.I,196000000);
assert.equal(result.months[8].totals.J,44800000);
assert.equal(result.months[8].totals.K,44800000/240800000);
assert.deepEqual(result.months[8].includedWeeks.map(w=>w.major),['38','39']);
assert.equal(result.months[7].status,'no_data');
assert.deepEqual(monthlyDemoWeeks('2025'),[]);
assert.deepEqual(monthlyDemoWeeks('__proto__'),[]);
assert.ok(buildMonthlyProfitSummary(weeks,'2025').months.every(m=>m.includedWeeks.length===0));
weeks[0].period.endDate='2026-10-01';
const boundary=buildMonthlyProfitSummary(weeks,'2026');
assert.equal(boundary.months[9].includedWeeks.length,1);
assert.equal(boundary.months[8].includedWeeks.length,1);
assert.equal(boundary.months[9].totals.J,21000000);
assert.equal(monthlyDemoWeeks('2026')[0].period.endDate,'2026-09-23');
console.log('Mobile monthly: web shared aggregator, sample totals, empty, cross-year, boundary and immutable fixtures passed');
