const assert=require('node:assert/strict');
const {monthlyDemoWeeks}=require('../lib/mobileMonthlyDemo');
const {buildMonthlyProfitSummary}=require('../lib/profitReportMonthly');
const {buildRaumPnlMonthlySummary}=require('../lib/raumPnlMonthly');
const weeks=monthlyDemoWeeks('2026');
const result=buildMonthlyProfitSummary(weeks,'2026');
assert.equal(result.months.length,12);
assert.equal(result.months[8].totals.C,240800000);
assert.equal(result.months[8].totals.I,196000000);
assert.equal(result.months[8].totals.J,44800000);
assert.equal(result.months[8].totals.K,44800000/240800000);
assert.deepEqual(result.months[8].includedWeeks.map(w=>w.major),['38','39']);
assert.equal(result.months[7].status,'no_data');
assert.deepEqual(monthlyDemoWeeks('2025'),[]);
assert.deepEqual(monthlyDemoWeeks('__proto__'),[]);
assert.deepEqual(monthlyDemoWeeks('2026','unknown'),[]);
assert.equal(monthlyDemoWeeks('2026','raum-profit')[0].totals.J,6300000);
assert.equal(monthlyDemoWeeks('2026','shilla-profit')[0].totals.J,4400000);
assert.equal(buildMonthlyProfitSummary(monthlyDemoWeeks('2026','raum-profit'),'2026').months[8].totals.J,12600000);
const hotel=buildRaumPnlMonthlySummary(monthlyDemoWeeks('2026','shilla-profit').map(w=>({OrderYear:'2026',MajorWeek:w.major,QuoteDate:w.period.endDate,SaleTotal:w.totals.C,CostTotal:w.totals.I,ProfitTotal:w.totals.J})));
assert.equal(hotel[0].month,'2026-09');
assert.equal(hotel[0].profit,8800000);
assert.equal(hotel[0].cost,34800000);
assert.ok(buildMonthlyProfitSummary(weeks,'2025').months.every(m=>m.includedWeeks.length===0));
weeks[0].period.endDate='2026-10-01';
const boundary=buildMonthlyProfitSummary(weeks,'2026');
assert.equal(boundary.months[9].includedWeeks.length,1);
assert.equal(boundary.months[8].includedWeeks.length,1);
assert.equal(boundary.months[9].totals.J,21000000);
assert.equal(monthlyDemoWeeks('2026')[0].period.endDate,'2026-09-23');
console.log('Mobile monthly: web shared aggregator, sample totals, empty, cross-year, boundary and immutable fixtures passed');
