const assert=require('node:assert/strict');
const {analysisKey,usableAnalysis,createPreanalysisCache,analysisGroups,TTL_MS}=require('../lib/pasteInboxPreanalysis');
const data={success:true,orders:[{custName:'친구',custMatch:{CustKey:1,CustName:'친구플라워'},items:[{inputName:'돈셀',prodKey:2,prodName:'CARNATION Doncel',qty:1,unit:'박스',action:'취소'}]},{custName:'울산신화',custMatch:{CustKey:3,CustName:'울산신화'},items:[{inputName:'문라이트',prodKey:4,prodName:'CARNATION Moon Light',qty:1,unit:'박스',action:'추가'}]}]};
async function main(){
  let calls=0,time=100,active=0,maxActive=0;
  const cache=createPreanalysisCache({now:()=>time,fetcher:async()=>{calls++;active++;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setTimeout(resolve,5));active--;return structuredClone(data);}});
  const [a,b]=await Promise.all([cache.read('원문','2026-39-02'),cache.read('원문','2026-39-02')]);
  assert.equal(calls,1,'same pending request shared');
  assert(usableAnalysis(a,'원문','2026-39-02',time));
  assert(!usableAnalysis(a,'원문','2025-39-02',time),'cross-year never reused');
  assert(!usableAnalysis(a,'원문 수정','2026-39-02',time));
  assert(!usableAnalysis(a,'원문','2026-39-02',time+TTL_MS));
  a.data.orders[0].items[0].qty=999;
  assert.equal(b.data.orders[0].items[0].qty,1,'simultaneous consumers receive independent drafts');
  const fresh=await cache.read('원문','2026-39-02');
  assert.equal(fresh.data.orders[0].items[0].qty,1,'editing draft cannot mutate cache');
  await Promise.all([cache.read('두번째','2026-39-02'),cache.read('세번째','2025-39-02')]);
  assert.equal(maxActive,1,'bounded sequential LLM calls');
  time+=TTL_MS;await cache.read('원문','2026-39-02');assert.equal(calls,4);
  await cache.read('원문','2026-39-02',{force:true});assert.equal(calls,5);
  await assert.rejects(cache.read('숨김','2026-39-02',{eligible:()=>false}),/화면 대기/);assert.equal(calls,5);
  const bounded=createPreanalysisCache({autoLimit:1,fetcher:async()=>data});
  await bounded.read('1','2026-39-02',{automatic:true});
  await assert.rejects(bounded.read('2','2026-39-02',{automatic:true}),/자동 분석/);
  await bounded.read('2','2026-39-02');
  let failures=0;const retry=createPreanalysisCache({fetcher:async()=>{if(!failures++)throw new Error('offline');return data;}});
  await assert.rejects(retry.read('x','2026-39-02'),/offline/);await retry.read('x','2026-39-02');
  assert.throws(()=>analysisKey('x','39-02'));
  const groups=analysisGroups(b.data);
  assert.deepEqual(groups.map(g=>g.customer),['친구플라워','울산신화']);
  assert.equal(groups[0].items[0].product,'CARNATION Doncel');assert.equal(groups[1].items[0].action,'+');
  assert.equal(groups[0].items[0].action,'−');assert(groups[1].items[0].matched);
  assert(!('applied' in groups[0].items[0]),'analysis is never committed ERP evidence');
  const mixed=structuredClone(data);Object.assign(mixed.orders[0].items[0],{qty:197,unit:'송이',quantitySource:'6박스 + 17스팀'});
  assert.equal(analysisGroups(mixed)[0].items[0].quantity,'6박스 + 17스팀');
  mixed.orders[0].items[0].mixedQuantityError='포장수 없음';assert(!analysisGroups(mixed)[0].items[0].matched);
  mixed.orders[0].custMatch=null;assert(!analysisGroups(mixed)[0].customerMatched);
  assert.deepEqual(analysisGroups({}),[]);
  console.log('paste inbox preanalysis: scope, cache, queue, failures, mixed quantities, advisory display passed');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
