import assert from 'node:assert/strict';
import {textWithoutExcludedLines,excludedTextRanges,toggleExcludedText} from '../lib/pasteExcludeText.js';
const source='37-2 중국 변경사항\n친구플라워\n블랙잭 10단 취소 <11번>\n은성꽃도매\n블랙잭 10단 추가';
const a=source.indexOf('<11번>'),b=a+5;
let ranges=toggleExcludedText(source,[],a,b);
assert.equal(ranges.length,1);
const filtered=textWithoutExcludedLines(source,ranges);
assert.ok(!filtered.includes('<11번>'));
assert.ok(filtered.includes('블랙잭 10단 취소'));
assert.ok(filtered.includes('블랙잭 10단 추가'));
assert.equal(filtered.split('\n').length,source.split('\n').length);
assert.deepEqual(toggleExcludedText(source,ranges,b,a),[]);
assert.equal(excludedTextRanges('앞에 삽입'+source,ranges).length,0,'stale offsets never exclude other text');
assert.deepEqual(toggleExcludedText(source,[],a,a),[]);
assert.deepEqual(toggleExcludedText(source,[],-1,2),[]);
const all=toggleExcludedText(source,[],a-3,b);
const split=toggleExcludedText(source,all,a,a+2);
assert.equal(split.length,2,'partial restore splits a range');
assert.equal(textWithoutExcludedLines('첫줄\n둘째\n셋째',[1]),'첫줄\n셋째','legacy line exclusions retained');
const emoji='🌼 화이트 메모 2박스';const s=emoji.indexOf('메모');
assert.ok(textWithoutExcludedLines(emoji,toggleExcludedText(emoji,[],s,s+2)).includes('🌼 화이트'));
assert.ok(textWithoutExcludedLines(emoji,toggleExcludedText(emoji,[],s,s+2)).includes('2박스'));
console.log('word exclusion: exact ranges, reverse selection, restore, stale text, Unicode and legacy passed');
