const assert=require('node:assert/strict');
const {mappedEvidenceSource}=require('../lib/pasteEvidenceSource');
const source=[{identity:'m1',message:'2025-37-02 카네이션\n수연\n미니아틱 1박스 추가',created_at:'2025-09-14T15:00:00+09:00'}];
const orders=[{custMatch:{CustKey:1,CustName:'수연원예'},items:[{prodKey:22,prodName:'MiniCarnation Artic/Ibis(화이트)',qty:1,unit:'박스',action:'추가'}]}];
const result=mappedEvidenceSource(source,orders);
assert.equal(result[0].created_at,source[0].created_at);
assert.equal(result[0].identity,'m1');
assert.match(result[0].message,/^2025-37-02/);
assert.match(result[0].message,/수연원예\nMiniCarnation Artic\/Ibis\(화이트\) 1박스 추가/);
assert.equal(source[0].message.includes('미니아틱'),true);
assert.equal(mappedEvidenceSource(source,[{...orders[0],custMatch:null}]),source);
assert.equal(mappedEvidenceSource(source,[{...orders[0],items:[{...orders[0].items[0],skip:true}]}]),source);
console.log('mapped evidence source: year, timestamp, identity and incomplete matching preservation passed');
const {normalizeScope,toFacts,parseMessages,pairRequests}=require('../lib/distributionLiveHistory');
const scope=normalizeScope({year:2025,week:'37-02',from:'2025-09-14',to:'2025-09-14'});
const facts=toFacts({customers:[{CustKey:1,CustName:'수연원예'}],products:[{ProdKey:22,ProdName:'MiniCarnation Artic/Ibis(화이트)',OutUnit:'박스',BunchOf1Box:1}],shipmentRows:[{eventId:1,year:'2025',week:'37-02',custKey:1,prodKey:22,unit:'박스',before:1,after:2,changeLocal:'2025-09-14T15:01:00.000',shipmentDateCount:1}]});
const matched=pairRequests(parseMessages(result,facts,{},scope),facts,scope);
assert.equal(matched[0].requests[0].shipmentEvents[0].before,1);
assert.equal(matched[0].requests[0].shipmentEvents[0].after,2);
const otherScope=mappedEvidenceSource([{...source[0],message:'36-02차 변경\n수연\n미니아틱 1박스 추가'}],orders);
assert.equal(parseMessages(otherScope,facts,{},scope)[0].requests[0].status,'AMBIGUOUS');
console.log('canonical mapping matches native quantity changes and rejects mismatched week');
