import assert from 'node:assert/strict';
import fs from 'node:fs';
import { rectanglePricingCellKeys, applyPricingCellCost } from '../lib/pricingCellSelection.js';

const products = [{ProdKey:30},{ProdKey:10},{ProdKey:20}];
const customers = [{CustKey:8},{CustKey:2},{CustKey:9}];
const rect = (startKey,endKey,ps=products,cs=customers) => rectanglePricingCellKeys({products:ps,customers:cs,startKey,endKey});
assert.deepEqual(new Set(rect('8_30','2_10')), new Set(['8_30','2_30','8_10','2_10']));
assert.deepEqual(new Set(rect('2_10','8_30')), new Set(rect('8_30','2_10')), 'reverse drag matches forward');
assert.deepEqual(rect('2_10','2_10'), ['2_10']);
assert.deepEqual(rect('base_30','2_10'), [], 'base cost excluded');
assert.deepEqual(rect('8_99','2_10'), [], 'hidden or stale product excluded');
assert.deepEqual(rect('88_30','2_10'), [], 'hidden customer excluded');
assert.deepEqual(rect('8_30','2_10',[]), []);
assert.deepEqual(new Set(rect('8_30','2_20',[products[0],products[2]])),new Set(['8_30','2_30','8_20','2_20']), 'displayed order only');
const costs = {'8_30':{cost:100},'2_30':{cost:200},'9_20':{cost:300}};
const localCosts = {'8_30':100,'2_30':200,'9_20':999};
const changed = new Set(['9_20']);
const apply = value => applyPricingCellCost({keys:['8_30','2_30'],value,localCosts,costs,changed});
const result=apply('500');
assert.equal(result.localCosts['8_30'],500);
assert.equal(result.localCosts['2_30'],500);
assert.equal(result.localCosts['9_20'],999,'unselected draft preserved');
assert.deepEqual(new Set(result.changed),new Set(['9_20','8_30','2_30']));
assert.equal(localCosts['8_30'],100,'does not mutate input');
assert.deepEqual(changed,new Set(['9_20']));
assert.equal(apply('0').localCosts['8_30'],0,'explicit zero accepted');
assert.equal(apply('12.5').localCosts['8_30'],12.5);
for(const invalid of ['', ' ', -1, Infinity, NaN, 'abc', null, false, [], {}]) assert.throws(()=>apply(invalid),`invalid ${invalid}`);
const restored=applyPricingCellCost({keys:['8_30'],value:100,localCosts:{'8_30':500},costs,changed:new Set(['8_30'])});
assert.equal(restored.changed.has('8_30'),false,'same-as-original is not dirty');
const page=fs.readFileSync(new URL('../pages/master/pricing.js',import.meta.url),'utf8');
assert.match(page,/rectanglePricingCellKeys/);
assert.match(page,/applyPricingCellCost/);
assert.match(page,/선택 영역 적용/);
assert.match(page,/드래그 선택/);
console.log('pricing cell rectangle and draft application tests passed');
