import assert from 'node:assert/strict';
import fs from 'node:fs';
const page = fs.readFileSync(new URL('../pages/orders/sales-paste.js', import.meta.url), 'utf8');
const api = fs.readFileSync(new URL('../pages/api/orders/index.js', import.meta.url), 'utf8');
const parser = fs.readFileSync(new URL('../pages/api/orders/parse-paste.js', import.meta.url), 'utf8');
const layout = fs.readFileSync(new URL('../components/Layout.js', import.meta.url), 'utf8');
assert.match(layout, /\/orders\/sales-paste[^\n]+영업부 붙여서 주문등록/);
assert.match(page, /apiPost\('\/api\/orders\/parse-paste'/, '기존 붙여넣기 매칭 API를 그대로 사용해야 합니다.');
assert.match(page, /source:\s*'sales-paste',[\s\S]{0,80}orderMode:\s*'ADD'/, '주문 전용 안전 정책으로 추가등록해야 합니다.');
assert.doesNotMatch(page, /\/api\/shipment\//, '영업부 페이지는 분배 API를 호출하면 안 됩니다.');
assert.match(page, /expectedCurrentQty/, '저장 직전 현재 주문수량 optimistic lock을 전달해야 합니다.');
assert.match(page, /resolveDetectedSalesPasteScope\(parsed\.detectedWeek, weekChoices\)/, '붙여넣기에서 감지한 차수를 선택 차수에 자동 반영해야 합니다.');
assert.match(page, /detectedScopeChange/, '차수 자동선택 중 입력 내용과 분석 결과가 지워지면 안 됩니다.');
assert.match(page, /apiGet\('\/api\/products\/search'/, '기존 공통 품목검색 랭킹 API를 사용해야 합니다.');
assert.match(page, /fetch\('\/api\/orders\/mappings'/, '사용자가 선택한 품목 매칭을 기존 저장매칭 시스템에 기록해야 합니다.');
assert.match(page, /replaceSalesPasteProduct\(rows, rowIndex, product, products\)/, '품목 수정 뒤 현재 주문과 등록 후 수량을 다시 계산해야 합니다.');
assert.match(page, /품목 검색·수정/, '자동 매칭된 행도 사용자가 검색하여 수정할 수 있어야 합니다.');
assert.match(page, /apiGet\('\/api\/orders\/my-customers',[\s\S]{0,100}custKey,[\s\S]{0,40}year,[\s\S]{0,40}week/, '등록 후 같은 연도·차수·업체 주문을 재조회해야 합니다.');
assert.match(api, /isSalesPasteSource/);
assert.match(api, /SELECT TOP 1 UserID FROM UserInfo WHERE UserID=@manager OR UserName=@manager/, '선택 담당자를 실제 UserInfo.UserID로 저장해야 합니다.');
assert.match(api, /ensureShipmentMaster = !isMyCustomerSource/, 'sales-paste는 ShipmentMaster를 생성하면 안 됩니다.');
assert.match(parser, /matchName: item\.matchName \|\| item\.inputName/, '콜 수국 같은 국가·품종 문맥을 공통 매칭 엔진에 전달해야 합니다.');
console.log('sales paste order UI/API tests passed');
