import assert from 'node:assert/strict';
import fs from 'node:fs';
const page = fs.readFileSync(new URL('../pages/orders/sales-paste.js', import.meta.url), 'utf8');
const api = fs.readFileSync(new URL('../pages/api/orders/index.js', import.meta.url), 'utf8');
const parser = fs.readFileSync(new URL('../pages/api/orders/parse-paste.js', import.meta.url), 'utf8');
const layout = fs.readFileSync(new URL('../components/Layout.js', import.meta.url), 'utf8');
assert.match(layout, /\/orders\/sales-paste[^\n]+영업부 붙여서 주문등록/);
assert.match(page, /apiPost\('\/api\/orders\/parse-paste'/, '기존 붙여넣기 매칭 API를 그대로 사용해야 합니다.');
assert.match(page, /source:\s*'sales-paste',[\s\S]{0,80}orderMode:\s*'ADD'/, '주문 전용 안전 정책으로 추가등록해야 합니다.');
assert.doesNotMatch(page, /\/api\/shipment\//, '영업부 페이지는 분배 API를 호출하면 안 됩니다.');
assert.match(page, /expectedCurrentQty/, '저장 직전 현재 주문수량 optimistic lock을 전달해야 합니다.');
assert.match(page, /resolveDetectedSalesPasteScope\(parsed\.detectedWeek, weekChoices\)/, '붙여넣기에서 감지한 차수를 선택 차수에 자동 반영해야 합니다.');
assert.match(page, /sourceText:\s*normalizeSalesPasteInputText\(text\)/, '현재 선택 차수보다 붙여넣은 원문의 차수를 우선 판정하도록 원문을 별도 전달해야 합니다.');
assert.match(page, /detectedScopeChange/, '차수 자동선택 중 입력 내용과 분석 결과가 지워지면 안 됩니다.');
assert.match(page, /apiGet\('\/api\/products\/search'/, '기존 공통 품목검색 랭킹 API를 사용해야 합니다.');
assert.match(page, /fetch\('\/api\/orders\/mappings'/, '사용자가 선택한 품목 매칭을 기존 저장매칭 시스템에 기록해야 합니다.');
assert.match(page, /replaceSalesPasteProduct\(rows, rowIndex, product, products\)/, '품목 수정 뒤 현재 주문과 등록 후 수량을 다시 계산해야 합니다.');
assert.match(page, /openMatchEditor\(index\)/, '자동 매칭된 행도 더보기에서 검색하여 수정할 수 있어야 합니다.');
assert.match(page, /suggestedProducts[\s\S]{0,180}slice\(0, 3\)/, '공통 매칭 엔진의 후순위 후보를 최대 3개 바로 표시해야 합니다.');
assert.match(page, /onClick=\{\(\) => applyMatchedProduct\(index, product\)\}/, '후순위 후보 클릭 한 번으로 저장 매칭을 변경해야 합니다.');
assert.match(page, />\s*더보기\s*<\/button>/, '후순위 후보에 원하는 품목이 없으면 더보기 버튼으로 전체 검색을 열 수 있어야 합니다.');
assert.match(page, /후순위 품목 더보기/, '더보기 화면에서 후순위 후보 목록임을 명확히 안내해야 합니다.');
assert.match(page, /검색 결과 · 클릭하면 바로 매칭 변경/, '검색창 아래 후순위 품목을 클릭하면 즉시 변경됨을 안내해야 합니다.');
assert.match(page, /LLM 정밀분석/, '사용자가 정확도 우선 LLM 분석이 적용됐음을 확인할 수 있어야 합니다.');
assert.match(page, /AI 인식 결과/, '기존 붙여넣기 주문등록처럼 AI가 읽은 결과를 별도 영역에 표시해야 합니다.');
assert.match(page, /buildSalesPasteAiPreview\(parsed\)/, 'API 원본 인식행을 최종 합산 전에 미리보기로 보존해야 합니다.');
assert.match(page, /category:\s*'sales-paste-analysis'/, '분석 시작·완료·실패를 운영 AppLog에서 추적할 수 있어야 합니다.');
assert.match(page, /분석 실행 로그/, '사용자도 현재 화면에서 분석 실행 상태를 확인할 수 있어야 합니다.');
assert.match(page, /변경 예정/, '현재 주문등록 현황 최상단에 등록 전 변경수량을 표시해야 합니다.');
assert.match(page, /방금 등록 변경/, '등록 후에도 직전 변경 전후 수량을 바로 확인할 수 있어야 합니다.');
assert.match(page, /order-change-summary/, '변경된 품목은 붉은 강조 영역으로 구분해야 합니다.');
assert.match(page, /paste-analysis-grid/, '붙여넣기 입력과 분석 결과는 같은 행에서 바로 비교할 수 있어야 합니다.');
assert.match(page, /<th>입력값<\/th>[\s\S]{0,80}<th>매칭값<\/th>/, '사용자 입력값과 전산 매칭값을 별도 열로 나란히 표시해야 합니다.');
assert.match(page, /className="col-input"[\s\S]{0,80}className="col-match"/, '입력값과 매칭값에 전용 넓은 열을 배정해야 합니다.');
assert.match(page, /salesPasteUnitOptions\(row\)/, '서버 환산식으로 검증된 단위만 행 선택지에 표시해야 합니다.');
assert.match(page, /replaceSalesPasteUnit\(rows, rowIndex, unit, products\)/, '단위 변경 시 현재 주문과 등록 후 수량을 다시 계산해야 합니다.');
assert.match(page, /\.customers\s*\{[\s\S]{0,100}flex-wrap:\s*wrap/, '업체 선택 버튼은 화면 폭에 맞춰 다음 줄로 내려가야 합니다.');
assert.match(page, /\.customers\s*\{[\s\S]{0,180}overflow-x:\s*hidden/, '업체 선택을 한 줄 가로 스크롤로 강제하면 안 됩니다.');
assert.match(page, /apiGet\('\/api\/orders\/my-customers',[\s\S]{0,100}custKey,[\s\S]{0,40}year,[\s\S]{0,40}week/, '등록 후 같은 연도·차수·업체 주문을 재조회해야 합니다.');
assert.match(api, /isSalesPasteSource/);
assert.match(api, /SELECT TOP 1 UserID FROM UserInfo WHERE UserID=@manager OR UserName=@manager/, '선택 담당자를 실제 UserInfo.UserID로 저장해야 합니다.');
assert.match(api, /ensureShipmentMaster = !isMyCustomerSource/, 'sales-paste는 ShipmentMaster를 생성하면 안 됩니다.');
assert.match(parser, /matchName: item\.matchName \|\| item\.inputName/, '콜 수국 같은 국가·품종 문맥을 공통 매칭 엔진에 전달해야 합니다.');
assert.match(parser, /suggestedProducts:\s*\(matched\.suggestedProducts \|\| \[\]\)\.map/, '공통 매칭 엔진의 순위 후보를 화면 응답에 포함해야 합니다.');
assert.match(parser, /normalizeSalesPasteInputText\(raw\)/, 'API 직접 호출에서도 줄 끝 역슬래시 수량행이 누락되면 안 됩니다.');
assert.match(parser, /sourceNaturalParsed\.detectedWeek[\s\S]{0,100}sourceCompactParsed\.detectedWeek[\s\S]{0,100}naturalParsed\.detectedWeek/, '붙여넣은 원문 차수를 문맥 헤더와 LLM 감지값보다 우선해야 합니다.');
assert.match(parser, /ORDER_PASTE_LLM_MODEL[\s\S]{0,100}claude-sonnet-4-5/, '비용보다 정확도를 우선하는 Sonnet 분석을 기본값으로 사용해야 합니다.');
assert.match(parser, /chooseSalesPasteParsedOrders\(/, 'LLM 결과를 규칙 결과가 무조건 덮어쓰지 말고 수량행 완전성으로 선택해야 합니다.');
assert.match(parser, /parseSource:\s*selectedParse\.source/, '분석 출처를 응답에 남겨 진단 가능해야 합니다.');
assert.match(parser, /analysisModel:\s*ORDER_PASTE_LLM_MODEL/, '분석 모델을 응답에 남겨 진단 가능해야 합니다.');
console.log('sales paste order UI/API tests passed');
