import assert from 'node:assert/strict';
import {reconcileWeekdayQuote as reconcile} from '../lib/weekdayQuoteReconciliation.js';
const day=(patch={})=>({date:'2026-09-17',detailFixed:true,weekDay:5,estimateQuantity:100.5,cost:10,amount:900,vat:105,...patch});
const block={cycle:{year:2026,majorWeek:'38',calendarState:'FOUND',days:Array.from({length:7},(_,i)=>({date:`2026-09-${17+i}`,calendarState:'FOUND'}))},productActuals:[{estUnit:'송이',outUnit:'박스',shipmentDates:[day(),day({estimateQuantity:50.5,cost:20,amount:900,vat:110})]}]};
const item=(patch={})=>({ProdKey:1,EstimateType:'정상출고',Quantity:152,Amount:1800,Vat:215,...patch});
const result=(items=[item()])=>({year:2026,majorWeek:'38',items});
assert.equal(reconcile(block,1,result()).state,'견적 일치');
assert.equal(reconcile(block,1,result()).quantity,152,'round each stored-cost group like EXE, not convert OutUnit');
assert.equal(reconcile(block,1,result()).unit,'송이');
assert.equal(reconcile(block,1,result([item({Quantity:151})])).state,'견적 불일치');
assert.equal(reconcile(block,1,result([item({Vat:200})])).state,'견적 불일치');
assert.equal(reconcile(block,1,{...result(),year:2025}).state,'범위 불일치');
assert.equal(reconcile(block,1,{...result(),majorWeek:'39'}).state,'범위 불일치');
assert.equal(reconcile(block,1,{error:'failed'}).state,'조회 필요');
assert.equal(reconcile(block,1,result([item({ProdKey:2})])).state,'견적 불일치','missing quote JOIN is not zero/matched');
const deducted=reconcile(block,1,result([item(),item({EstimateType:'불량차감',Quantity:-2,Amount:-20,Vat:-2})]));
assert.equal(deducted.state,'견적 일치');assert.equal(deducted.netQuantity,150);assert.equal(deducted.amount,1993);
const invalid=structuredClone(block);delete invalid.productActuals[0].shipmentDates[0].cost;
assert.equal(reconcile(invalid,1,result()).state,'대조 확인 필요');
const unfixed=structuredClone(block);unfixed.productActuals[0].shipmentDates.forEach(row=>row.detailFixed=false);
assert.equal(reconcile(unfixed,1,result()).state,'대조 확인 필요');
assert.equal(reconcile(unfixed,1,result([])).state,'대조 확인 필요','positive unfixed source is not quote absence');
const wrongUnit=structuredClone(block);wrongUnit.productActuals.push({estUnit:'단',shipmentDates:[]});
assert.equal(reconcile(wrongUnit,1,result()).state,'대조 확인 필요');
assert.equal(reconcile(block,1,result([item({Amount:NaN})])).state,'수량·금액 확인 필요');
const unknownUnit=structuredClone(block);unknownUnit.productActuals.push({estUnit:null,shipmentDates:[]});
assert.equal(reconcile(unknownUnit,1,result()).state,'대조 확인 필요','unknown unit is not filtered out');
const withManagement={...result(),managementItems:[item()]};
assert.equal(reconcile(block,1,withManagement).managementQuantity,152);
assert.equal(reconcile(block,1,withManagement).state,'견적 일치');
assert.equal(reconcile(block,1,{...withManagement,managementItems:[item({Quantity:151})]}).state,'견적 불일치','date round vs grouped round difference is explicit');
assert.equal(reconcile(block,1,{...withManagement,managementError:'failure'}).state,'관리 대조 확인 필요');
assert.equal(reconcile(block,1,{...withManagement,managementItems:[item({Amount:NaN})]}).state,'관리 대조 확인 필요');
const bothDeducted={...result([item(),item({EstimateType:'불량차감',Quantity:-2,Amount:-20,Vat:-2})]),managementItems:[item(),item({EstimateType:'불량차감',Quantity:-2,Amount:-20,Vat:-2})]};
assert.equal(reconcile(block,1,bothDeducted).managementQuantity,150,'actual management total includes deductions');
assert.equal(reconcile(block,1,bothDeducted).state,'견적 일치');
const noCalendar=structuredClone(block);noCalendar.productActuals[0].shipmentDates[0].weekDay=null;
assert.equal(reconcile(noCalendar,1,result([])).state,'대조 확인 필요','missing date/calendar association is not quote absence');
const outside=structuredClone(block);outside.productActuals[0].shipmentDates[0].date='2026-09-24';
assert.equal(reconcile(outside,1,withManagement).state,'대조 확인 필요','same saved totals do not hide a cycle-outside allocation');
const undated=structuredClone(block);undated.productActuals[0].shipmentDates=[];undated.productActuals[0].shipmentOutQuantity=2;
assert.equal(reconcile(undated,1,result([])).state,'대조 확인 필요');
console.log('Weekday quote reconciliation: saved EstUnit quantities/cost rounding, normal/net amounts, unknown/mismatch/year gates passed');
