import assert from 'node:assert/strict';
import {buildHorizontalWeekdayMatrix} from '../lib/weekdayHorizontalMatrix.js';
import {buildWeekdayWebExportSnapshot} from '../lib/weekdayWebExportSnapshot.js';
const cycle={offset:0,year:2026,majorWeek:'40',startDate:'2026-10-01',calendarState:'FOUND',days:Array.from({length:7},(_,i)=>({date:`2026-10-0${i+1}`,label:['목','금','토','일','월','화','수'][i],orderWeek:i<4?'40-01':'40-02',calendarState:'FOUND'}))};
const actual=[{year:2026,orderWeek:'40-01',prodKey:1,prodName:'웹에서 변경한 품목',flowerName:'카네이션',custKey:533,outUnit:'박스',state:'FOUND_UNFIXED',detailRows:1,shipmentOutQuantity:5,shipmentDates:[{date:'2026-10-04',shipmentQuantity:3}]},
{year:2026,orderWeek:'40-02',prodKey:1,custKey:533,outUnit:'박스',state:'NO_SHIPMENT',detailRows:0,shipmentOutQuantity:null,shipmentDates:[]}];
const baseline=[{custKey:533,year:2026,orderWeek:'40-01',rows:[{prodKey:1,quantity:5,unit:'박스',shipmentDates:[{date:'2026-10-04',quantity:3}]}]},
{custKey:533,year:2026,orderWeek:'40-02',rows:[{prodKey:1,quantity:0,unit:'박스',shipmentDates:[]}]}];
const matrix=buildHorizontalWeekdayMatrix([cycle],[],actual,baseline);
let model=buildWeekdayWebExportSnapshot(matrix);
const value=(label)=>model.rows[0].values[model.columns.find(col=>col.label===label).key];
assert.equal(model.rows[0].name,'웹에서 변경한 품목');
const englishRow={...matrix.rows[0],name:'CARNATION Brut'};
assert.equal(buildWeekdayWebExportSnapshot({...matrix,rows:[englishRow]}).rows[0].name,'카네이션 브루트');
assert.equal(buildWeekdayWebExportSnapshot({...matrix,rows:[{...englishRow,name:'CARNATION 브루트'}]}).rows[0].name,'카네이션 브루트');
assert.equal(buildWeekdayWebExportSnapshot({...matrix,rows:[{...englishRow,displayName:'브루트 지정명'}]}).rows[0].name,'브루트 지정명');
assert.equal(buildWeekdayWebExportSnapshot(buildHorizontalWeekdayMatrix([cycle],[],actual.map(row=>({...row,displayName:'품목 등록 한글명'})),baseline)).rows[0].name,'품목 등록 한글명','comparison metadata reaches export through matrix');
assert.ok(model.columns.every(column=>!column.label.includes('2026')),'year appears only in internal identity');
assert.equal(value('10/04\n일'),3,'canonical day total is already normal + Wilson');
assert.equal(value('40-1 합계'),3);assert.equal(value('40-1 잔량'),2);
const wilson={year:2026,orderWeek:'40-01',custKey:533,prodKey:1,date:'2026-10-04',unit:'박스',status:'CURRENT',expectedTotal:3,wilsonQuantity:1};
model=buildWeekdayWebExportSnapshot(matrix,'테스트',{custKey:533,wilsonRecords:[wilson]});
assert.equal(value('10/04\n일'),2);assert.equal(value('10/04\n윌슨 일'),1);assert.equal(value('10/04\n일 합계'),3);
assert.equal(value('40-1 합계'),3,'split columns must not double count Wilson');
assert.throws(()=>buildWeekdayWebExportSnapshot(matrix,'테스트',{custKey:533,wilsonRecords:[{...wilson,expectedTotal:99}]}),/윌슨 분류/);
assert.throws(()=>buildWeekdayWebExportSnapshot(matrix,'테스트',{custKey:533,wilsonDrafts:[{...wilson,wilsonQuantity:9}]}),/윌슨 분류/);
const drafts=[{custKey:533,year:2026,orderWeek:'40-01',prodKey:1,prodName:'웹에서 변경한 품목',flowerName:'카네이션',unit:'박스',date:'2026-10-04',quantity:4}];
model=buildWeekdayWebExportSnapshot(buildHorizontalWeekdayMatrix([cycle],drafts,actual,baseline));
assert.equal(value('10/04\n일'),4);assert.equal(value('40-1 합계'),4);assert.equal(value('40-1 잔량'),1);
model=buildWeekdayWebExportSnapshot(buildHorizontalWeekdayMatrix([cycle],drafts,actual,baseline),'테스트',{custKey:533,wilsonRecords:[wilson],wilsonDrafts:[{...wilson,expectedTotal:4,wilsonQuantity:2}]});
assert.equal(value('10/04\n일'),2);assert.equal(value('10/04\n윌슨 일'),2);assert.equal(value('10/04\n일 합계'),4);
model=buildWeekdayWebExportSnapshot(matrix,'요일선택',{wilsonDay:'화'});
assert.ok(model.columns.some(col=>col.label==='10/06\n윌슨 화'));assert.ok(!model.columns.some(col=>col.label==='10/04\n윌슨 일'));
const previous={...cycle,offset:-1,year:2025};
model=buildWeekdayWebExportSnapshot(buildHorizontalWeekdayMatrix([previous,cycle],drafts,actual,baseline));
assert.ok(model.columns.some(col=>col.label==='40-1 합계' && col.key.includes('|2025|')));
assert.equal(model.rows[0].values[model.columns.find(col=>col.label==='40-1 합계' && col.key.includes('|2025|')).key],null,'same week previous year never contributes');
const extra={...matrix.rows[0],prodKey:2,name:'검색으로 숨겨진 신규 장미',flowerNames:['장미']};
model=buildWeekdayWebExportSnapshot({...matrix,rows:[extra,...matrix.rows]});
assert.deepEqual(model.rows.map(row=>row.name),['웹에서 변경한 품목','검색으로 숨겨진 신규 장미']);
assert.equal(model.rows.length,2,'all source rows included without visible-row filtering');
const otherCycle={...cycle,offset:1,majorWeek:'41',startDate:'2026-10-08'};
const multiUnit={...matrix.rows[0],blocks:[...matrix.rows[0].blocks,{...matrix.rows[0].blocks[0],cycle:otherCycle,unit:'송이'}]};
model=buildWeekdayWebExportSnapshot({cycles:[cycle,otherCycle],rows:[multiUnit]});
assert.deepEqual(model.rows.map(row=>row.unit),['박스','송이']);
assert.equal(model.rows[0].values[model.columns.find(column=>column.label==='41차 합계').key],null,'different-unit cycle stays in its own row');
assert.equal(model.rows[1].values[model.columns.find(column=>column.label==='40차 합계').key],null);
console.log('Full web export snapshot: current names, absolute draft totals, 5-3=2 balance, Wilson once, cross-year unknown and all products passed');
