import assert from 'node:assert/strict';
import {buildHorizontalWeekdayMatrix as build,weekdayQuantityLabel as label,weekdayProductLabel as name,hasHorizontalShipmentQuantity as visible} from '../lib/weekdayHorizontalMatrix.js';
import {SHIPPING_DAYS,shiftDate} from '../lib/weekdayEstimateCycle.js';
const cycle={offset:0,year:2026,majorWeek:'38',calendarState:'FOUND',days:SHIPPING_DAYS.map((day,index)=>({...day,date:shiftDate('2026-09-17',index),orderWeek:`38-${day.suffix}`,calendarState:'FOUND'}))};
const entry=(suffix,quantity,dates=[])=>({year:2026,orderWeek:`38-${suffix}`,custKey:533,confirmedAt:'2026-10-01T00:00:00.000Z',confirmedBy:'fixture',rows:[{prodKey:1,prodName:'ALSTROEMERIA Mila',flowerName:'알스트로',quantity,unit:'단',shipmentDates:dates.map(([date,quantity])=>({date,quantity,orderWeek:`38-${suffix}`}))}]});
const bases=[entry('01',48,[['2026-09-17',32],['2026-09-18',16]]),entry('02',32,[['2026-09-21',32]])];
const actual=(suffix,quantity,dates)=>({year:2026,orderWeek:`38-${suffix}`,prodKey:1,prodName:'ALSTROEMERIA Mila',flowerName:'알스트로',outUnit:'단',state:'FOUND_UNFIXED',shipmentOutQuantity:quantity,shipmentDates:dates.map(([date,shipmentQuantity])=>({date,shipmentQuantity}))});
const current=[actual('01',48,[['2026-09-17',16],['2026-09-21',32]]),actual('02',24,[['2026-09-22',24]])];
const get=(rows=current,records=bases,plans=[])=>build([cycle],plans,rows,records).rows[0].blocks[0];
let block=get();
assert.equal(block.initial01.quantity,48);assert.equal(block.initial02.quantity,32);
assert.equal(block.remaining01,32,'moved from Thu/Fri to Mon remains first-segment remainder');
assert.equal(block.remainingMajor,8,'80 initial minus all72 dated allocations');
assert.equal(block.initialChange,-8);
assert.equal(block.days[0].initial,32);assert.equal(block.days[0].initialDelta,-16);
assert.equal(block.days[1].displayCurrent,0);assert.equal(block.days[1].initialDelta,-16,'removed date shows0(initial16), not disappears');
assert.equal(block.days[4].effectiveOrderWeek,'38-01','actual source business week retained on Monday');
assert.equal(block.days[4].initial,0);assert.equal(block.days[4].initialDelta,32);
assert.equal(block.days[5].initial,0);assert.equal(block.days[5].initialDelta,24);
const snapshot=JSON.stringify({bases,current,cycle});get();assert.equal(JSON.stringify({bases,current,cycle}),snapshot,'all inputs immutable');
assert.equal(get(current,[bases[0]]).remainingMajor,null,'02 initial missing is not0');
assert.equal(get(current,bases.map(row=>({...row,year:2025}))).remaining01,null,'prior year baseline cannot leak');
assert.equal(get(current,bases.map(row=>({...row,orderWeek:'39-01'}))).remaining01,null,'other week not initial');
const mixed=structuredClone(current);mixed[1].outUnit='박스';assert.equal(get(mixed).remainingMajor,null);
const unknown=structuredClone(current);unknown[0].shipmentDates[0].shipmentQuantity=null;assert.equal(get(unknown).remainingMajor,null);
const invalidDate=structuredClone(current);invalidDate[0].shipmentDates[0].date='2026-02-30';assert.equal(get(invalidDate).remainingMajor,null);
const over=[actual('01',100,[['2026-09-17',100]]),actual('02',0,[])];assert.equal(get(over).remaining01,-52);assert.equal(get(over).remainingMajor,-20,'excess isnegative never clamp0');
const cancelled=['01','02'].map(suffix=>({...actual(suffix,0,[]),state:'NO_SHIPMENT',shipmentOutQuantity:null}));
const cancelledMatrix=build([cycle],[],cancelled,bases);block=cancelledMatrix.rows[0].blocks[0];
assert.equal(block.currentTotal,0);assert.equal(block.remainingMajor,80);assert.equal(block.initialChange,-80);assert.ok(visible(cancelledMatrix.rows[0]),'initial positive retains cancelled row');
for(const outUnit of ['박스',null,'mystery']) {
  const mismatched=build([cycle],[],cancelled.map(row=>({...row,outUnit})),bases);
  assert.ok(visible(mismatched.rows[0]),'baseline-positive cancelled row remains visible when current unit changes/is unknown');
  assert.equal(mismatched.rows[0].blocks[0].remainingMajor,null,'mismatched units never get a fabricated remainder');
  assert.equal(mismatched.rows[0].blocks[0].productInitials[0].quantity,48,'raw baseline amount retained');
}
const draft={id:'d',year:2026,orderWeek:'38-01',prodKey:1,quantity:10,unit:'단',date:'2026-09-17'};
block=get(current,bases,[draft]);assert.equal(block.remaining01,32);assert.equal(block.projectedRemaining01,38);assert.equal(block.projectedRemainingMajor,14,'draft remaining is separate');
assert.equal(get(current,bases,[draft,{...draft,id:'d2'}]).projectedRemainingMajor,null,'duplicate proposalsnotcollapsed');
const outside=[actual('01',48,[['2026-09-24',48]]),actual('02',0,[])];block=get(outside);assert.equal(block.remainingMajor,80,'out-of-cycle allocationnotconsumed in38days');assert.equal(block.currentTotal,48,'business quantity stillpreserved');
for(const [qty,expected] of [[48,'48(3)'],[16,'16(1)'],[8,'8(0.5)'],[0,'0(0)'],[-16,'-16(-1)']])assert.equal(label(qty,{flowerNames:['알스트로']},'단'),expected);
assert.equal(label(48,{flowerNames:['ALSTROMERIA']},'BUNCH'),'48(3)');
assert.equal(label(48,{flowerNames:['장미']},'단'),'48');assert.equal(label(3,{flowerNames:['알스트로']},'박스'),'3');
assert.equal(label(null,{flowerNames:['알스트로']},'단'),'—');assert.equal(label('',{flowerNames:['알스트로']},'단'),'—');
assert.equal(name({name:'ROSE / Mondial White 60cm'}),'Mondial White 60cm');assert.equal(name({name:'CARNATION Moon Light'}),'Moon Light');
assert.equal(name({name:'HYDRANGEA White (화이트)'}),'White (화이트)');assert.equal(name({name:'MiniCarnation Arctic'}),'MiniCarnation Arctic','separate category remains intact');
console.log('Initial weekday matrix: immutable dated baselines, segment/major remainders, cancellations, drafts,year/unit guards,48(3) and product label passed');

const candidates=current.map(row=>({...entry(row.orderWeek.slice(-2),row.shipmentOutQuantity),provisional:true}));
const candidateBlock=(records=[],previews=candidates,rows=current)=>build([cycle],[],rows,records,previews).rows[0].blocks[0];
block=candidateBlock();
assert.equal(block.provisional01.quantity,48);assert.equal(block.provisional02.quantity,24);
assert.equal(block.initial01,null);assert.equal(block.initialMajor,null);
assert.equal(block.initialChange,null);assert.equal(block.remaining01,null);assert.equal(block.remainingMajor,null);
assert.ok(block.days.every(day=>day.initial===null && day.initialDelta===null),'unconfirmed current quantities never fabricate historical changes');
block=candidateBlock(bases);assert.equal(block.initial02.quantity,32);assert.equal(block.provisional02,null,'stored immutable baseline wins');
assert.equal(candidateBlock([],candidates.map(row=>({...row,year:2025}))).provisional01,null);
assert.equal(candidateBlock([],candidates.map(row=>({...row,orderWeek:'39-01'}))).provisional01,null);
assert.equal(candidateBlock([],candidates.map(row=>({...row,error:'failed read'}))).provisional01,null);
assert.equal(candidateBlock([],candidates.map(row=>({...row,provisional:false}))).provisional01,null);
assert.equal(candidateBlock([],[candidates[0],candidates[0]]).provisional01,null,'duplicate source is ambiguous');
for(const quantity of [null,'',-1,Infinity])assert.equal(candidateBlock([],candidates.map(row=>({...row,rows:row.rows.map(item=>({...item,quantity}))}))).provisional01,null);
assert.equal(candidateBlock([],candidates.map(row=>({...row,rows:row.rows.map(item=>({...item,quantity:0}))}))).provisional01.quantity,0);
assert.equal(candidateBlock([],candidates.map(row=>({...row,rows:row.rows.map(item=>({...item,unit:'박스'}))}))).provisional01,null);
const missingStoredProduct=bases.map(row=>({...row,rows:[]}));
assert.equal(candidateBlock(missingStoredProduct).provisional01,null,'a product absent from stored initial snapshot cannot fall back to today');
console.log('Provisional baseline: display-only current values, immutable priority, no fabricated changes/remainders, year/week/unit/error/zero guards passed');

const original=[actual('01',25,[['2026-09-17',5],['2026-09-20',20]]),actual('02',0,[])];
const originalBases=[entry('01',25,[['2026-09-17',5],['2026-09-20',20]]),entry('02',0,[])];
const minusOne={...draft,quantity:4};
const inspect=(records=originalBases,previews=[],edits=[minusOne],rows=original)=>build([cycle],edits,rows,records,previews).rows[0].blocks[0];
block=inspect();
assert.equal(block.remaining01,0,'stored remainder remains unchanged');
assert.equal(block.remainder01View.value,1,'5→4 immediately releases1 in displayed draft remainder');
assert.equal(block.remainderMajorView.value,1);
assert.equal(block.remainder01View.label,'초안 예상');
assert.equal(block.effectiveTotal,24);assert.equal(block.effectiveInitialChange,-1);
const originalPreviews=originalBases.map(record=>({...record,provisional:true}));
block=inspect([],originalPreviews);
assert.equal(block.remainder01View.value,1);assert.equal(block.remainderMajorView.value,1);
assert.equal(block.remainder01View.label,'미확정·초안');
assert.equal(block.initial01,null);assert.equal(block.initialChange,null);
assert.equal(block.days[0].initial,null,'preview does not fabricate original date comparison');
assert.equal(inspect([],originalPreviews,[]).remainder01View.label,'미확정 예상');
assert.equal(inspect([],originalPreviews,[{...minusOne,quantity:0}]).remainder01View.value,5);
assert.equal(inspect([],originalPreviews,[minusOne,{...minusOne,id:'other'}]).remainder01View.value,null);
assert.equal(inspect([],originalPreviews,[{...minusOne,quantity:-1}]).remainder01View.value,null);
assert.equal(inspect([],originalPreviews,[{...minusOne,unit:'박스'}]).remainder01View.value,null);
assert.equal(inspect([],originalPreviews.slice(0,1)).remainderMajorView.value,null,'missing02 is unknown, notzero');
assert.equal(inspect([],originalPreviews.map(record=>({...record,year:2025}))).remainder01View.value,null);
assert.equal(inspect(originalBases.map(record=>({...record,rows:[]})),originalPreviews).remainder01View.value,null,'stored missing product cannot fall back to current preview');
const malformed=structuredClone(original);malformed[0].shipmentDates[0].shipmentQuantity=null;
assert.equal(inspect(originalBases,[],[minusOne],malformed).remainder01View.value,null);
console.log('Readable remainder view:5→4 releases1, provisional/draft labels, historical preservation, invalid/duplicate/unit/year/missing-source guards passed');
